### ISSUE TITLE
Style: Loading icon disruptive

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy.org#101]
What do folks feel about removing the concentric circle blip that appears on loading each page?  I, for one, find it quite disruptive on every click / page load.

**Comment by rgommers** [comment]
+1 from me

**Comment by shaloo** [comment]
+1 for removing

**Comment by joelachance** [comment]
+1 here as well. This is default hugo-fresh behavior, so we can update it.

**Comment by joelachance** [comment]
What would be preferred to the current loader?

**Comment by rgommers** [comment]
No animation at all, just load the page as fast as possible I'd say.

**Comment by MarsBarLee** [comment]
Here's the website without the loading circle, as the original issue requested.
![WithoutAnyAnimations](https://user-images.githubusercontent.com/46167686/72574534-67bedc00-3897-11ea-8d90-6be1baca723f.gif)

Here's the website without any animations the loading circle or any fade-in animation, as Ralf suggested.
![WithoutLoadingFrontPage](https://user-images.githubusercontent.com/46167686/72574546-6db4bd00-3897-11ea-9e31-99399b30bd46.gif)

Here's the website without the loading circle but a fade-in animation only for the front page
![WithLoadingFrontPage](https://user-images.githubusercontent.com/46167686/72574554-73120780-3897-11ea-9f24-d71cc5641e50.gif)

I like third one the most, even if it's a little bit slower for that page. The first page feels too slow and the second one feels a little too adrupt.

What do you guys think?

**Comment by joelachance** [comment]
Nice, well done! I also like the third one a lot, but I think I'd end up picking the second. The time between initial page request and usability (I think there's probably an acronym for this I'm forgetting) is most important on the homepage. I'll admit the fade doesn't *really* affect it, I think it'll appear to users as an extra unnecessary moment.

I'm splitting hairs here, but 2 or 3 I think would be great.

**Comment by InessaPawson** [comment]
@MarsBarLee , thank you for going the extra mile by giving us several options. I believe most of the numpy.org visitors will more appreciate the speed that comes with the second option.

**Comment by rgommers** [comment]
Nice @MarsBarLee, both options look great to me! Now that you have both already, you could also put both in with one enabled one disabled and a simple if-statement to switch between them (assuming that's easy now). Then we can try out the prettier option 3, and if it does indeed feel too slow we can just flip the switch.

**Comment by stefanv** [comment]
Fairly strong preference for nr 2 on my part, but could live with nr 3.  Think of all the times you've watched Powerpoint slides; the animations are cute, but grow tiresome quickly, and thereafter you just want to get to the information.

**Comment by rgommers** [comment]
Fixed, closing. Thanks @MarsBarLee for the fix and everyone for feedback!

@MarsBarLee if in one of your commit messages you would include `closes gh-101` or `fixes gh-101`, then this issue would have auto-closed. Useful for next issues perhaps.
