### ISSUE TITLE
Installation instructions can be confusing to newcomers

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy.org#102]
The current installation instructions are beautifully simple; well done!

That said, they may be confusing to newcomers.  Conda: "To install NumPy do X or Y" without giving advice on when to use which.  When using pip do X or Y if Python comes with your OS.  Most users may not have any idea whether Python comes with their OS, or whether that is the version they're using.  Perhaps `pip install numpy --user` works fine in a venv too, and can be the only command recommended.

**Comment by rgommers** [comment]
Yep, still going to polish this. Also, we want to have a widget like on https://pytorch.org/get-started/locally/, @InessaPawson is working on that.


>  Perhaps `pip install numpy --user` works fine in a venv too, and can be the only command recommended.

Nope, `--user` with virtual/conda envs is terrible imho, since it _couples_ environments that should be separate from each other. The only reason to use `--user` is in a Linux distro style setup, where Python is installed in a place with restricted permissions (e.g. with `apt`). It's a thing from the past I think, using environments is the thing to teach these days.

**Comment by matthew-brett** [comment]
`pip install --user` does not work in a virtualenv, sadly:

```
$ pip install --user transforms3d
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

I personally run with my --user environment nearly all the time, and dip into virtualenvs when I have to check dependencies or try another Python version.  That's what I'd recommend for pip users.

**Comment by rgommers** [comment]
> `ERROR: Can not perform a '--user' install.`

nice, that's an improvement over what `pip` used to do, which was just install anyway and create a mess.

Unfortunately there's no universal command that can be given. I think we have to have concise install instructions (as we have now), but add some notes for new users that link out to a page with more detail, to explain about distributions, ways to obtain Python, etc.

I think we should really be teaching use of per-project/activity environments (whether conda or virtualenv). Anything else tends to end in:

![image](https://user-images.githubusercontent.com/98330/70669415-32392a00-1c2b-11ea-9f75-13c971907cb5.png)

**Comment by matthew-brett** [comment]
I think having multiple environments adds a layer of complexity to the install that will only be useful for a relatively small subset of people (i.e. developers, working on more than one project).

I used to use virtualenvs all the time, but with the improvement in CI,  it became less important for me to test multiple Python versions.  Then I got bored of switching between virtualenvs, and found I was happy having a God-knows-what-state standard environment, and an occasional sterile-field virtualenv when I needed to test something specific, like older package versions or Python versions.

**Comment by rgommers** [comment]
We should at least teach the concept. I've seen way to many users (including me) with a "God-knows-what-state standard environment" that were in a world of pain, and afraid to `rm -rf` it. There's also `poetry` and `venv` for wheel users that may be worth knowing about.

**Comment by stefanv** [comment]
Thanks, I wasn't aware of the coupling with `--user`. When it worked, I presumed it had ignored the flag, since I was in a virtual env, but yikes.

So, yes, I think the widget will help because you can choose at least Conda, pip, or say Debian, and then have about the same amount of text you see now for all systems.

@InessaPawson I was thinking of doing a similar widget for skimage using Vue.js. I would be curious to hear what you have in mind to use for this one.

**Comment by InessaPawson** [comment]
@stefanv I was thinking Bootstrap.

**Comment by rgommers** [comment]
With the changes in gh-179, the commands on the main page are now down to:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/98330/76691769-dda0b300-664e-11ea-8f4d-9cb24e000e51.png">

That should address the initial concern I think.
