### ISSUE TITLE
Content: ML Tab

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#103]
Add content for Machine Learning tab under Ecosystem on landing page

**Comment by shaloo** [comment]
Updated- refer to PR https://github.com/numpy/numpy.org/pull/106

**Comment by shaloo** [comment]
<img width="925" alt="Screenshot 2019-12-13 at 8 02 39 PM" src="https://user-images.githubusercontent.com/5890484/70807655-fe553480-1de3-11ea-967a-abb8d3ed7327.png">

**Comment by rgommers** [comment]
this is done, closing
