### ISSUE TITLE
Homepage - Case studies - Layout/Design

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#129]
Add the ‘Case studies’ segment below 'In a nutshell' using a tile layout grid and link to the case study/studies.

**Comment by InessaPawson** [comment]
@joelachance, could you implement this layout https://github.com/numpy/numpy.org/issues/82#issuecomment-571007398?

**Comment by joelachance** [comment]
Yep! Still finishing some interactive shell stuff, but i'll work on some layout improvements next.

**Comment by joelachance** [comment]
@InessaPawson, I'm going to close this issue, it seems to be a duplicate of #82.

**Comment by rgommers** [comment]
done in gh-159, closing
