### ISSUE TITLE
Add license text or a link to it to new website

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#138]
@rgommers Would you like to add the content of this [page](github.com/numpy/numpy.org/blob/master/old-content/license.rst) to the new website?

**Comment by rgommers** [comment]
Thanks for the suggestion Inessa. No, I don't want a license page - I much prefer to link to the license file on GitHub, that avoids maintaining duplicate content. 

I'll leave this issue open till an appropriate link is put in.

**Comment by shaloo** [comment]
Taking a shot at this one as suggested by @rgommers.  Using https://github.com/numpy/numpy/blob/master/LICENSE.txt in and linking license info mentioned in 'Open Source' section under 'In a Nutshell'.
