### ISSUE TITLE
NumPy Showcase page 

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#141]
This page will contain information about key NumPy case studies that showcase its capabilities to a wider audience.

*  Add draft content in a 'Showcase Page'
*  Link respective anchors on this showcase page to NumPy.org landing page case studies tiles once @joelachance addresses #129 layout for the same.

**Comment by InessaPawson** [comment]
Thank you for taking a lead on this, Shaloo! Would you mind to continue communicating about the content for the “NumPy case studies” block in Issue #82. Let’s try not to duplicate issues.

**Comment by shaloo** [comment]
There are two aspects - content and design as described by @rgommers . Duplicate of #82, hence closing.
