### ISSUE TITLE
Fix Homepage spacing

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#152]
There's too much whitespace between content on the homepage. Improve spacing between sections on the homepage.

- [x] Give the shell 4 borders
- [x] Shrink the space above and below the shell
- [x] Fix key features media query (Goes back to a single row for very wide desktops)
- [x] Change key features background to separate sections
- [x] Remove any additional spacing around sections with too much

**Comment by rgommers** [comment]
Also, left over from gh-156 is the styling of the right side of the interactive shell: https://github.com/numpy/numpy.org/issues/156#issuecomment-578491847

**Comment by stefanv** [comment]
I built today, and this still seems like a blocker for release.

**Comment by rgommers** [comment]
Yep, @joelachance said on Slack he has work in progress for this
