### ISSUE TITLE
Review content pages

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#156]
Let's improve the content page styling a bit.

- [x] The current width is too wide for desktop. I think a `max-width: 900px` seems reasonable.
- [x] Some of the shortcuts are broken. Make sure we're using `h2` and `h3` headers.
- [x] Update shortcuts width to make it slightly wider to avoid text wrapping.

Create any necessary shortcodes to improve content pages.

**Comment by shaloo** [comment]
@joelachance, I noticed that on safari (running on MacBook pro),  if I enable the NumPy command console, it does not show up fully - it gets clipped on RHS.  Nor is there any scroll interface to view to the right-most edge of the console if someone is typing a long code line.  Am I missing something or is this a bug?  See screenshot below:

<img width="1188" alt="Screenshot 2020-01-26 at 12 26 47 PM" src="https://user-images.githubusercontent.com/5890484/73134307-1e227e00-405b-11ea-82e4-f8f42faecd69.png">

**Comment by joelachance** [comment]
@shaloo that is by design. I thought it looked nicer, but if people find it misleading or want something else, we can do that.
What you see is what you get-- there's no scrolling, and nothing off the right hand side of your screen.

**Comment by rgommers** [comment]
I was wondering what would happen for long lines; scrollbar shows up within the terminal itself:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/98330/73444120-3a266800-4358-11ea-8eaf-023492f7bbba.png">

I don't have a strong opinion, but if I'd have to choose I'd say that a box with 4 rounded corners would be a little better.

**Comment by joelachance** [comment]
I'll add the interactive shell work to #152 since it's a bit outside the scope of this ticket.
