### ISSUE TITLE
front page could (should?) include a link to the github repo

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy.org#157]
Unless I am mistaken, there is no link from numpy.org to github.com/numpy/numpy.  I am personally partial to the classic "fork me on github" ribbon, but it doesn't have to have that, as long as it's easily found.

**Comment by rgommers** [comment]
Good point @anntzer. The new site has that already in the footer. We'll launch that soon (current master + pending PRs are close to ready, <1 month I'd say), so won't be putting work in the old Sphinx-based site anymore.

Since this is already done, I'll close the issue.
