### ISSUE TITLE
Update Tabs Content

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#158]
Abbreviate tabs content.

- [ ] Limit to a single image per tab
- [ ] Specifically for the "array libraries" tab, move the overview of libraries to the "array computing" page

Abbreviate additional text as necessary.

**Comment by shaloo** [comment]
Ref https://github.com/numpy/numpy.org/pull/153

This issue will be used to address @rgommers comments wrt tab content:

>>
* I think the content can indeed be reduced a little, in particular limit to a single image per tab (visualization and data science have two now). let's do that in a separate PR though. I also still need to edit the text.
* Specifically for the "array libraries" tab, we can move the overview of libraries to the "array computing" tab (we considered that before), and then have larger logos/text on that separate page. Then no need to have a carousel there; carousels are nice for unrelated items, but here it's good to have a single overview
>>

**Comment by rgommers** [comment]
This also is on my list for this weekend.

**Comment by rgommers** [comment]
This is looking much better now, thanks for the input everyone!
