### ISSUE TITLE
Rendering seems to be off on high resolution screens

### ISSUE THREAD

**Issue by seberg** [numpy/numpy.org#168]
On my computer, the website is rendered not very well. Also at the bottom the case studies are not all three next to each other. This happens both with chromium and with firefox.

See attached image, let me know if you need some other information.
![Screenshot from 2020-02-19 18-45-08](https://user-images.githubusercontent.com/61977/74896099-39c23100-5348-11ea-9c0a-e19bbee6a741.png)

**Comment by joelachance** [comment]
@seberg, could you be more specific? We're aware of the whitespace and are going to re-style very soon.

We're going to comb over the homepage and fix all the spacing and minor issues, which I think you might be alluding to.

**Comment by seberg** [comment]
Hmm, yeah, maybe the abundance of whitespace is just more extreme, the case studies are not all next to eac hother as well, but not sure if that is not the same, known, problem:
![Screenshot from 2020-02-20 08-12-59](https://user-images.githubusercontent.com/61977/74955141-0c619b80-53b9-11ea-961d-cf5e2f773674.png)

**Comment by joelachance** [comment]
Typically it's good to not let content spill out too wide. I can tell your resolution is pretty high too, which will add to the whitespace a bit :) That being said, I agree, we can get those all in one row.

**Comment by seberg** [comment]
I am not actually what bit me/us the wrong way, maybe the font also look just small compared to the space the whole layout takes?

**Comment by joelachance** [comment]
Good observation, I'll take a look!

**Comment by MarsBarLee** [comment]
This is how the site looks like in 2560 x 1440, which was the resolution the issue opener used.
![numpyoriginal](https://user-images.githubusercontent.com/46167686/76905551-8d0c9e00-6878-11ea-8904-51b43da64759.png)

This is the mock-up with some changes I'm thinking of implementing.
![numpyedited](https://user-images.githubusercontent.com/46167686/76905577-9ac22380-6878-11ea-89d6-0f26eec110a0.png)
Changes include centering the content to the middle of the page and removing the white space.  

Does anyone have any thoughts or suggestions?

**Comment by joelachance** [comment]
I'm updating the shell (above the fold) section, so expect that to change. I'm moving the NumPy title/CTA & the shell into rows vs. columns, so I think it'll look nicer and more centered.

As far as the rest, I think what you have looks nice! I'd like to try and maintain a max-width similar to the width of the nav bar, which I believe matches what you have in your layout.

**Comment by seberg** [comment]
Yeah, I think maintaining a max-width is probably a very good idea and solves all these issues (no matter what other layout changes are upcoming).

**Comment by MarsBarLee** [comment]
Hi @seberg, made some changes in gh-183
