### ISSUE TITLE
Updated donor information for NumFOCUS

### ISSUE THREAD

**Issue by lisamartin72** [numpy/numpy.org#18]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-numpy/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by stefanv** [comment]
@lisamartin72 Can you please provide us with the new widget code?

See https://help.salsalabs.com/hc/en-us/articles/115000019054-Publish-and-Widgets#widgets-for-external-web-pages

**Comment by lisamartin72** [comment]
Of course!

```
<div id="71a600e8-a8c5-4018-a12f-4c4c91f49a37">
    <script type="text/javascript" src="https://default.salsalabs.org/api/widget/template/67824ba6-266f-4c29-b3eb-5639162a417c/?tId=71a600e8-a8c5-4018-a12f-4c4c91f49a37" ></script>
</div>
```

Let me know if you need anything else.

Best,
Lisa

**Comment by rgommers** [comment]
Hi @lisamartin72, welcome! And thanks for the details.

@stefanv Gina mentioned to me that Flipcause will stop working by mid April. Do you or anyone at BIDS have time to take care of this?

**Comment by stefanv** [comment]
On Wed, 20 Mar 2019 12:19:10 -0700, Ralf Gommers wrote:
> @stefanv Gina mentioned to me that Flipcause will stop working by mid
> April. Do you or anyone at BIDS have time to take care of this?

Yes, sure, this should be quick; I can take it on.

**Comment by rgommers** [comment]
awesome, thanks

**Comment by mattip** [comment]
I can make this part of #17, which reminds me I should push it forward

**Comment by mattip** [comment]
@lisamartin72 this code creates a "donate form" (the orange box in the screenshot below), we want a "Donate Button" instead.

![Screenshot from 2019-03-21 09-22-49](https://user-images.githubusercontent.com/823911/54738073-5f383f00-4bbb-11e9-959b-d6b9239f9fdc.png)

**Comment by lisamartin72** [comment]
```<a href="https://numfocus.salsalabs.org/donate-to-numpy" target="_blank" style="background:#FFA500;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#222222;font-family:Arial, Helvetica, sans-serif;display:inline-block;">Donate Now!</a>```

**Comment by rgommers** [comment]
this was done a while ago, closing
