### ISSUE TITLE
Google Analytics for numpy.org

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#198]
Set up an account with Google Analytics.
See the docs for integration on Hugo: https://gohugo.io/templates/internal/#google-analytics

**Comment by joelachance** [comment]
This looks like it would be about 2 minutes of work, but we'll need a tracking ID.
@rgommers, who might be able to sign up for GA and get a tracking ID? I'm happy to do it, but assuming we might want this under a NumPy account.

**Comment by rgommers** [comment]
I have no experience with GA, but seems from things like https://www.optimizesmart.com/understanding-account-property-view-users-google-analytics/ that it just needs a Gmail account, and then can be shared? We have no numpy-wide account, only a shared Google Groups thing but that won't help. 

Maybe best if I set it up with the same Gmail account that's also connected to the NumPy Twitter account? (which is basically my email but with a special `+numpyteam` attached)

**Comment by joelachance** [comment]
That sounds good to me! Thank you for doing that.

**Comment by seberg** [comment]
@rgommers Ok, can you make sure to add that info to the NumPy logistics repo? (just to be sure, I bet you would have)

**Comment by rgommers** [comment]
Okay, set up. Tracking ID: `UA-162151853-1`. 

If anyone wants access, please let me know with which email address and I'll add you.

**Comment by joelachance** [comment]
I can look at this if you add me: jlachance1@gmail.com.

**Comment by rgommers** [comment]
Thanks @joelachance. Done, you should have full edit rights for that GA account.

**Comment by InessaPawson** [comment]
> If anyone wants access, please let me know with which email address and I'll add you.

@rgommers I'd like to have access. albuscode@gmail.com Thank you!

**Comment by rgommers** [comment]
Added you @InessaPawson
