### ISSUE TITLE
Getting Started Guide: To do work items post launch

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#214]
Ref: https://github.com/numpy/numpy.org/pull/189

and

>> I can take GettingStarted/Quickstart up next once I am done cleaning up 45 and case studies. Is that ok?

@shaloo I think it will be easier to rework https://numpy.org/devdocs/user/quickstart.html after the website is launched, because then it can link back to Install and Learn. What you can do now though is to review it and make an overview of what needs changing. We've recently started doing this (see numpy/numpy#15760 for an example), planning out what should be on a docs page and reviewing that should yield better results than just starting to write.

**Comment by InessaPawson** [comment]
I'm closing this issue as the NumPy quickstart has been revised.
