### ISSUE TITLE
Add News Section

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#219]
Add “News” section to the home page, right below the "Get Started" button, to share announcements about the NumPy project development milestones, community initiatives, events, etc.

**Comment by InessaPawson** [comment]
_Copying the comment from PR #222_
Just an image for now: 

![numpynews_warmblack](https://user-images.githubusercontent.com/43481325/80484549-3deb7a00-899b-11ea-8ce0-5bf39c25da3f.png)

This is how it looks in a prototype: https://github.com/numpy/numpy.org/pull/221#issuecomment-620559287

@rgommers I need your input for the content of this section. Once everything is confirmed, I'll create a .svg version and submit a PR.

**Comment by rgommers** [comment]
So just to make sure: what I deduce from the text in this screenshot is that the news in the bar has one major topic (typically a new release, but could be an event) indicated in large font, and then one or more detail snippets in smaller font related to that?

**Comment by InessaPawson** [comment]
You are correct in your deduction, @rgommers. This image/bar could be linking to a page that provides more information about the displayed piece of news.

**Comment by InessaPawson** [comment]
@rgommers Are you happy with the current content of the news section?

**Comment by rgommers** [comment]
Yes, I think it's fine - given the form factor it's just a highlight and way to link to the full page. The alternative would be to go with a much bigger design element, which I'm not sure fits well in the current layout.

**Comment by InessaPawson** [comment]
@rgommers I was asking whether highlighting the latest stable release was a good idea, or we should consider something else (e.g. CZI grant, a certain NEP, upcoming Season of Docs, etc.).

**Comment by rgommers** [comment]
Oh okay, yes I think the latest release would be best to start with.
