### ISSUE TITLE
Misc Mobile rendering issues and CSS suggestions

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy.org#227]
The shell-content wiht blocks of code make the website rendering looks weird on mobile
```
.shell-content {
    min-width: 500px;
}
```

Seem to interfere wit mobile rendering issue by forcing the page to be too wide, which lead to while gap on the left:

Before/After removing the 500px min width
<img width="461" alt="Screen Shot 2020-05-13 at 10 00 00" src="https://user-images.githubusercontent.com/335567/81842260-9163d900-9500-11ea-8814-4d7170a9cbe7.png">
<img width="464" alt="Screen Shot 2020-05-13 at 10 00 07" src="https://user-images.githubusercontent.com/335567/81842254-8f9a1580-9500-11ea-8496-832f1cdccd0d.png">

Can't be completely removed as the code blocks become unreadable, but I'm guessing those can be tweaked with media-screen queries

also:

```
.section3-box-content {
    margin: 30px 30px 30px 0;
}
```

<img width="423" alt="Screen Shot 2020-05-13 at 10 03 28" src="https://user-images.githubusercontent.com/335567/81842638-2ebf0d00-9501-11ea-8f96-f29ff483ce64.png">

Is not centered on mobile view either. 30px on all side is likely what you want on small screen (via media queries as well?). 

`.section2` seem to have the same issue but less visible.

There also seem to be a few screen width transition that are either off by one pixel between files or used only once:

```
// syle.css

// only transition at at 320
@media only screen and (max-width: 320px) { 

// syle.css only transition at at 400
@media only screen and (max-width: 400px) {
```

```

// section2.css only transition at at 420
@media only screen and (max-width: 425px) {
    .section2 .container {
```

Both of the following transition are off by 1px or 2px from the one in the theme used (bulma) and might lead to edge case behavior.
```
// contents.css
@media only screen and (max-width: 1088px) {
    .shortcuts-container {
        display: none;
    }
}
```

```
// section2.css
@media only screen and (max-width: 1090px) {
    .section2 .container {
        margin: 0 6vw;
    }
}
```

Chrome says there are transitions at 1087px,1088px, and 1090px maybe all those values should be collapsed ? Usually the less transitions the better has you have less screen width to test for rendering issues. These off-by-one are common even in framework as it is rarely clear in min-screen-width/max-screen-width if the end value is included or not. 

New website looks great otherwise will try to review a content and give feedback ! Good work !

**Comment by joelachance** [comment]
@Carreau Thank you for the feedback! We'll take a look.

**Comment by joelachance** [comment]
I'm finding that our Hugo theme is contributing a good amount to the media-query pollution, cleaned that up as much as possible.

@Carreau , thanks again!
