### ISSUE TITLE
Remove one of the two logos at the top of the front page

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#229]
As discussion on gh-221, there are now two logos on the front page. Discussion:

>>>    What do you think of removing the smaller logo just from the homepage?

>> Dynamically hiding a logo in the header seems a little elaborate. I agree having the double logo is a little odd (but who knows, maybe it looks better with the new logo!). Maybe easier to remove the bigger one?

> I do like the larger version of the logo next to the title NUMPY. However, if it is the only way to minimize the number of the logos on the homepage, I'm willing to sacrifice it.

**Comment by joelachance** [comment]
My preference would be to remove the logo in the nav bar and keep the 'exponential' logo with the NumPy title, until the user scrolls down (nav bar logo shows after user scrolls). 

There's potential that's the harder fix (although we may need to simply remove the logo config from the nav partial), and if other people prefer the other option of removing the exponential logo, then I'm game!

**Comment by rgommers** [comment]
I'm happy with removing the navbar logo unconditionally.

**Comment by InessaPawson** [comment]
> My preference would be to remove the logo in the nav bar and keep the 'exponential' logo with the NumPy title, until the user scrolls down (nav bar logo shows after user scrolls).
> 
+1 for the above. I thought there was a way!;) Thank you, @joelachance!

**Comment by rgommers** [comment]
We merged the PR for this, closing.
