### ISSUE TITLE
README should specify *extended* Hugo

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#231]
A user who installs Hugo by following the Getting Started link in the README will get the failure
```
error: failed to transform resource: TOCSS: failed to transform "style.sass"
```
when they run `hugo server`.

Users need to install the extended version, e.g.,
```
sudo apt-get install ./hugo_extended_0.70.0_Linux-64bit.deb
```
which I don't think is mentioned in the page we're linking to.

Extended Hugo is a requirement of the [Hugo Fresh theme](https://themes.gohugo.io/hugo-fresh/) (see `Troubleshooting` at the bottom the page).

**Comment by rgommers** [comment]
That's right, good catch. You're not the first one to run into that @bjnath. Would you be able to open a PR to fix the README?

**Comment by bjnath** [comment]
Wasn't able to push the PR:
```
(doc-build-38) bjn@lynnfield:~/numpy_newsite/numpy.org$ git push origin hugo_install_readme
ERROR: Permission to numpy/numpy.org.git denied to bjnath.
```

**Comment by rgommers** [comment]
That's because the standard workflow is for you to "fork" this repo (button at right top of the page). You then push your changes to a new branch in your own fork, and from there you can send a PR.

The process is described at https://numpy.org/devdocs/dev/index.html#development-process-summary (just change the name of the repo from `numpy` to `numpy.org`).

**Comment by rgommers** [comment]
The rationale for that is that is we let every contributor create new branches in this repo, it would get very messy very quickly. Pretty much every open source project uses this "send PR from forks" method.

**Comment by bjnath** [comment]
I did fork:
![image](https://user-images.githubusercontent.com/6691888/82315872-fb193280-9999-11ea-9db1-521145e335f2.png)

and the step that failed was right out of https://numpy.org/devdocs/dev/index.html#development-process-summary:

![image](https://user-images.githubusercontent.com/6691888/82315837-eb015300-9999-11ea-8d3d-04d288202c54.png)

**Comment by bjnath** [comment]
OK, I see -- I have origin set the same as upstream:
```
(doc-build-38) bjn@lynnfield:~/numpy_newsite/numpy.org$ git remote -v
origin  git@github.com:numpy/numpy.org.git (fetch)
origin  git@github.com:numpy/numpy.org.git (push)
upstream        https://github.com/numpy/numpy.org.git (fetch)
upstream        https://github.com/numpy/numpy.org.git (push)
```
I'll fix it and try again.

**Comment by bjnath** [comment]
All set, filed PR #241

**Comment by bjnath** [comment]
PS, @rgommers, thanks for clarifying how it works. I was following the instructions but couldn't visualize what was happening.

**Comment by rgommers** [comment]
No worries, thanks for the PR!

One more tip: if you add in your commit message next time `closes gh-231` or `fixes gh-231`, then this issue gets auto-closed when your PR is merged.

**Comment by bjnath** [comment]
Great tip, will do! Thanks.
