### ISSUE TITLE
Broken links on new site

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#232]
A link checker run on the new site found these 8 broken links:
```
1  case-studies/cricket-analytics/  Image credit for Cricket Pose Estimator  (12029)
2  community/                       'contributors' in first line (404)
3  /                                CuPy logo in Ecosystem->Array Libraries (404)
4  /                                xtensor link in Ecosystem->Array Libraries (empty href)
5  /team                            stylesheet link to /static/css/styles.css (404)
6  /learn                           'SciPy Lectures' (404)
7  /learn                           'NumPy User Guide' (404)
8  /contribute                      'User Guide' under "Developing educational materials" heading (404)
```
In addition the `hreflang="nl"` `link` tag in the header picks up a number of missing pages.

(Strictly speaking, this should be 9 separate issues. I'll be happy to resubmit the issues that way if we prefer.)

**Comment by rgommers** [comment]
Thanks @bjnath! Good idea to run a link checker, we should do that in CI at some point.

One issue is definitely preferred over 9 separate ones here, since that's less noisy and easy to fix in one go.

**Comment by bjnath** [comment]
> One issue is definitely preferred

In my old life each would have a different owner based on who'd created the page. This is a nice change.

**Comment by bjnath** [comment]
I will try to find where the links should go and PR these before launch.

**Comment by rgommers** [comment]
> In my old life each would have a different owner based on who'd created the page. This is a nice change.

If we'd be that formal, not many people would want to contribute I think. We tend to operate on trust a bit more:)

**Comment by bjnath** [comment]
Actually, while you're here...I'm fixing these links, and have gotten to:
```
* [NumPy User Guide](https://numpy.org/devdocs/user/index.html)
```
on the /learn page. I can't figure out what I should change this to. `https://numpy.org/devdocs`?

**Comment by bjnath** [comment]
And in fact I have almost the same problem with the last broken link, on the /contribute page:
```
NumPy's [User Guide](https://numpy.org/devdocs/user) can use a lot of help -
```
Somebody with a mean streak might say "even the NumPy team can't find the NumPy user guide," but I'd never be so mean.

**Comment by rgommers** [comment]
> I can't figure out what I should change this to. `https://numpy.org/devdocs`?

yes indeed
