### ISSUE TITLE
Serial commas

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#237]
There's precedent in the NumPy site for use of the serial comma -- that is, a comma before the final 'and' in a list of three things or more:

`dev/index.rst:240:` 
the documentation. Matplotlib, SciPy, and IPython are also required.

`dev/conduct/code_of_conduct.rst:37:`
2. Be empathetic, welcoming, friendly, and patient. We work together to resolve
<br>
The new site does not use it:

`./public/index.html:670:`
Several of these newer libraries such as CuPy, Sparse and Dask,

`./public/index.html:205:`
NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms and more.

Based on precedent (and the [Google guide](https://developers.google.com/style/commas), if we adopt it), the new site should use serial commas too. 

I'd be willing to write the PR.

**Comment by bjnath** [comment]
I added serial commas in the Ecosystem edit of PR #242 but haven't checked them sitewide.

**Comment by InessaPawson** [comment]
I've been using serial commas in my content submissions for the website. We had 3 other contributors (at least). I'll check for consistency in their writing.

**Comment by rgommers** [comment]
I've probably been guilty of using this inconsistently. +1 for using it everywhere, and following the Google style guide.
