### ISSUE TITLE
Make shell example cut-and-pastable

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#240]
Users will want to cut and paste the example at the left onto the shell, so it should be presented as one block, with the intervening text (e.g., "Create a 2-D array") being changed into comments.

![image](https://user-images.githubusercontent.com/6691888/82317440-40d6fa80-999c-11ea-9953-b03ca6b54cc6.png)

Playing the role of dumb user I cut and pasted just the middle section since it seemed the most interesting, and of course saw

![image](https://user-images.githubusercontent.com/6691888/82318385-c3ac8500-999d-11ea-94c3-185eed6a89e0.png)

**Comment by rgommers** [comment]
That's a fair comment. I liked the look of proper text rather than code comments, but copy-pasting is useful. I can take this along in the final cleanup before launch.
