### ISSUE TITLE
Change the color of the `hero-title` font and footer background

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#246]
Change the color of the `hero-title` font and background color of the footer to Warm Black      (#013243) to match the rest of the dark elements.

**Comment by joelachance** [comment]
@InessaPawson, I've got some questions here (this is not done, of course):

![Screen Shot 2020-05-21 at 4 20 25 PM](https://user-images.githubusercontent.com/3891660/82607761-09747380-9b7f-11ea-8a9f-569ccd19c07f.png)

Do we want to update the nav background color and link color as well?
Of course the logo and subtitle font color should be white, but thoughts on the button color?
Last, this bleeds into the news section, any thoughts there?

**Comment by InessaPawson** [comment]
@joelachance The following changes need to be made:
1. change the color of the letters in the title “NUMPY” to Warm Black (#013243). The color of the background should remain white.
2. change the background color of the footer to Warm Black (#013243).

Nothing radical.:)

**Comment by joelachance** [comment]
I knew this was supposed to be simpler :) Check out the PR, @InessaPawson!

**Comment by InessaPawson** [comment]
It's a green light from me! Thank you, @joelachance!
