### ISSUE TITLE
Use anchor in developer guide link on /contribute page

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#247]
The link to the [developer guide](https://numpy.org/devdocs/dev/index.html) in /contribute points to a page that looks almost identical to the page the user is currently on.

I propose adding an anchor to the link (https://numpy.org/devdocs/dev/index.html#development-process-summary) so the user skips the intro and goes immediately to the guide.

**Comment by bjnath** [comment]
PR in #248

**Comment by rgommers** [comment]
That sounds good to me. 

@bjnath please note that it's also fine to submit the PR directly without opening a separate issue, and simply putting the rationale in the PR description. Saves on effort and notifications:)

**Comment by bjnath** [comment]
Thanks -- that'll put some minutes back in my day.
