### ISSUE TITLE
Have 'install' nav link point to /installing-python-and-numpy-guide

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#249]
`/install` is a skimpy page that points to a more thorough page, `/installing-python-and-numpy-guide`. 

It feels frustrating to visit the page, get inadequate instructions, and be pointed elsewhere for the real skinny.

I suggest we eliminate that page and rename `installing-python-and-numpy-guide`  so the `install` nav link points to it. 

A short intro section can take the place of the current `install` page if we feel an overview is needed.

**Comment by rgommers** [comment]
We have further improvements coming with a widget, see gh-212. That will present more info in a compact format.

I think a lot is quite detailed in that other page and about install Python itself, not about installing NumPy. So I don't think that makes sense to throw at users, most will already have Python.

**Comment by bjnath** [comment]
Fair enough -- thanks.

**Comment by rgommers** [comment]
Actually I'm rethinking this. Not all users may need the content on the second page, but I wish all users understood such things. I'll try moving it to the main page and see if it works better.
