### ISSUE TITLE
Develop and embed on the website interactive tutorials

### ISSUE THREAD

**Issue by dashohoxha** [numpy/numpy.org#26]
Using https://www.katacoda.com/ we may develop and embed on the website a couple of interactive tutorials for beginners (which can be based on the existing NumPy tutorials). This may make it easier and more fun for beginners to get started.

The infrastructure is supplied for free by Katacoda, so we don't need to run or maintain any server for it. The only limitation is that the duration of the training session for a student is 1 hour, and then he can reload the browser and start a fresh session. I think this time is enough and anyway we should not make tutorials that last longer than one hour.

Building an interactive tutorial is very easy and everybody can learn it in a short time. The code of the tutorial is just a bunch of JSON and markdown files (for the configuration of the environment and for the steps of the tutorial). It can be saved on your preferred git repository (GitHub, GitLab, Bitbacket, etc.) and Katacoda pulls it from there and builds the tutorial environment (docker image). You also need to set a webhook on the repository, so that whenever you make some changes (commits) Katacoda is notified to refresh the content of the tutorial.

**Comment by rgommers** [comment]
I think I'll close this, given that we now have an interactive terminal and no further plans to do interactive tutorials on this website. We did create a new `numpy-tutorials` repo and are likely to hook that up to Binder once we have a good amount of content.

Thanks for the idea @dashohoxha
