### ISSUE TITLE
Order of tabs in ecosystem widget

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#267]
Of all the tabs, considering both visual appeal and content, I like "data science", "scientific domains" and "array libraries" better than "visualization" and "machine learning". This is easy to switch around, especially what we choose to be first matters, because it's opened by default.

My proposed order:
1. scientific domains
2. data science
3. array libraries
4. machine learning
5. visualization

The scientific domain image is probably the one that captures best how broad the ecosystem is, hence putting that on `#1`.

Thoughts?

**Comment by shaloo** [comment]
How about  array libraries before 'data science'?  That way positioning-wise  'data science' is right below 'ecosystem' and gets eyeballs first.  Also, array libraries have a big role in NumPy consumption (indirectly), that could get us hits from newer users.

**Comment by rgommers** [comment]
Completely agree @shaloo, thanks. Actually I came to the same conclusion when making these changes.
