### ISSUE TITLE
Measure website traffic pre/post launch of new site

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#269]
We now have Google Analytics integration, that data will only show up post-launch. 

For Cloudflare data from Aug 2019, see https://github.com/numpy/numpy.org/issues/30#issuecomment-519292657.

Cloudflare gives us the current (23 May 2020) status pre-launch:

![image](https://user-images.githubusercontent.com/98330/82738360-44b9a280-9d37-11ea-97ad-5c78aa99c7d6.png)

![image](https://user-images.githubusercontent.com/98330/82738350-3bc8d100-9d37-11ea-93f6-85cba1eb2c78.png)

![image](https://user-images.githubusercontent.com/98330/82738371-631f9e00-9d37-11ea-972c-eda6c4d452c9.png)

**Comment by rgommers** [comment]
We launched halfway through May 24th (third data point from the right here):

![image](https://user-images.githubusercontent.com/98330/82987882-9a70a200-9ff8-11ea-9658-b45588a68bf7.png)

Unclear why visitor numbers were up in the couple of days pre-launch, however so far it looks like we're going to get a structural increase. Let's check back in some days/weeks.

**Comment by rgommers** [comment]
Data from last week (3 Aug 2020):

<img width="771" alt="image" src="https://user-images.githubusercontent.com/98330/89232847-a8d6cd80-d5e8-11ea-9ac7-fc95cd4b72e1.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/98330/89232881-bd1aca80-d5e8-11ea-9f59-81bbbf588b34.png">


Only a very modest increase, which is a little puzzling.

**Comment by rgommers** [comment]
Not sure why Google Analytics doesn't see nearly as much visitors, 14x less:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/98330/89233100-34505e80-d5e9-11ea-8409-dd61c4c5f7f3.png">

**Comment by rgommers** [comment]
Adding SimilarWeb's statistics before the pre-launch data is no longer visible:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/98330/92904158-ec5ffb00-f422-11ea-9bc2-055e618e8307.png">

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/98330/92904221-f84bbd00-f422-11ea-81ec-ed1ec4b6b13b.png">

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/98330/92904273-07326f80-f423-11ea-87a9-bbee9b79ec80.png">

**Comment by InessaPawson** [comment]
> Not sure why Google Analytics doesn't see nearly as much visitors, 14x less:
> 
One of the reasons is that GA is blocked in China, one of NumPy’s top user and developer locales.

**Comment by rgommers** [comment]
Data from today:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/98330/103176181-e544e780-486f-11eb-81ba-dff73adcb6d9.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/98330/103176221-466cbb00-4870-11eb-83d9-ba35b88bb033.png">

That should be enough, I'll close the issue.
