### ISSUE TITLE
Make docs navigation header point to numpy.org rather than scipy.org

### ISSUE THREAD

**Issue by adeak** [numpy/numpy.org#292]
At https://numpy.org/doc/stable/ which is directly accessible from numpy.org via the top documentation link, the top navigation link says "Scipy.org", and both links do in fact lead back to scipy.org and docs.scipy.org, respectively.

I suspect this is already on your radar and will be affected by the Sphinx theme manipulations (edit: and keeping the docs.scipy.org link might be on purpose), but I couldn't find an explicit mention after searching the existing issues.

**Comment by rossbar** [comment]
Nice catch - I think this is an issue with the most current 1.18 docs having been built and uploaded before the link badging change. Looking into it...

**Comment by adeak** [comment]
Perhaps fixing this and potentially renaming "Docs" to "All docs" could also help with https://github.com/numpy/numpy.org/issues/293#issuecomment-633262863. We'd be back at "single click takes you to numpy.org/doc".

**Comment by rossbar** [comment]
> At https://numpy.org/doc/stable/ which is directly accessible from numpy.org via the top documentation link, the top navigation link says "Scipy.org", and both links do in fact lead back to scipy.org and docs.scipy.org, respectively.

This should now be fixed via numpy/doc@20a1b0f for the stable docs (1.18.4). The tags should now point to numpy.org and numpy.org/doc, respectively.

> Perhaps fixing this and potentially renaming the "Docs" button to "All docs" could also help with #293 (comment). We'd be back at "single click takes you to numpy.org/doc".

This is a nice suggestion - making the "Doc" tag a bit more descriptive may help. I think this would be an update to the sphinx theme rather than numpy.org website (as you noted in the comments above).

**Comment by adeak** [comment]
@rossbar very nice, thank you for the fix! I'm closing this issue because the main point is fixed. I'll copy over my button renaming suggestion to the other issue to have it in a more relevant place.
