### ISSUE TITLE
Consider having an easier path for older versions of the documentation

### ISSUE THREAD

**Issue by adeak** [numpy/numpy.org#293]
This is probably a feature request.

Currently the straightforward "Documentation" link at numpy.org takes the user to https://numpy.org/doc/stable/ which is the docs of the current stable version. This is what the overwhelming majority of users is looking for, so this is great! But if I'm looking for the dev docs or the docs of a specific older version of numpy, I think I can only find that by clicking on the top "Docs" link and picking the version I need.

I understand that it might not be trivial (from a semantic point of view) to somehow put a direct link to other versions from a version-specific front page of the documentation (currently v1.18). And wanting to have access to specific versions might be niche enough that the current setup will work just fine.

And it also makes sense just having to click that "Docs" link to get other docs versions.

**Comment by rossbar** [comment]
I had the same thought as @adeak - I agree that the current default link location (doc/stable) is sensible and probably what most people want, though the `numpy.org/doc` landing page is more general in that it has links to all the old versions, the current stable version, and the devdocs.

It would be nice to have an easier, "more clickable" way to navigate to `numpy.org/doc` though I'm not sure what the best way to go about it is. Thanks for the great site!

**Comment by adeak** [comment]
To copy my suggestion from another issue, we could rename the "Docs" button in the navigation bar to "All docs" or something similar. This would make it more obvious that one can find alternative versions there.

**Comment by bjnath** [comment]
@adeak Agreed, the way it is now isn't the way it should be. We do have a goal of providing smooth access to earlier releases directly from the doc pages. Unfortunately this improvement is bundled with broader structural changes so it's been slow to appear.  But I believe we want what you want -- a dropdown menu on the main docs page to pick a version.

**Comment by melissawm** [comment]
Now that we have adopted the [PyData theme](https://github.com/numpy/numpy/pull/17074), there's a chance the version switcher will be available sometime in the future (see for example https://docs.spyder-ide.org/current/index.html - the Spyder team has mentioned they would be able to help bring that feature upstream)

**Comment by adeak** [comment]
A version switcher would be the ultimate solution to this problem. Let's hope it will work out :)

**Comment by InessaPawson** [comment]
The version switcher has been added to the top navigation bar of https://numpy.org/doc/stable/. I'm closing the issue.

**Comment by prjemian** [comment]
> The version switcher has been added to the top navigation bar of https://numpy.org/doc/stable/. I'm closing the issue.

@InessaPawson - Can you point to the PR, issue, or commit hash where this work was done?  I want to do similar with my projects.

**Comment by mattip** [comment]
It is part of the [pydata theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/) we use, and was implemented in a series of PRs I found by [searching for switcher](https://github.com/numpy/numpy/pulls?q=is%3Apr+switcher+is%3Aclosed)

**Comment by prjemian** [comment]
@mattip Thanks for the links!
