### ISSUE TITLE
Switch Bioinformatics + Bayesian Inference headers

### ISSUE THREAD

**Issue by peterjc** [numpy/numpy.org#303]
The images and the projects in those columns strongly suggest the two captions (Bioinformatics + Bayesian Inference) got swapped under "Ecosystem" on https://numpy.org/

i.e. Edit ``layouts/partials/scientific-domains.html``

Also most of us would write "Bioinformatics" as one word, but I understand if "Bio Informatics" is needed for layout purposes, but if so maybe add a hypen?

**Comment by rgommers** [comment]
Fixed now, thanks for reporting.
