### ISSUE TITLE
redirect https://numpy.org/conduct.html

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy.org#306]
First google result for "Numpy code of conduct" points to https://numpy.org/conduct.html, which now is https://numpy.org/code-of-conduct/

can a conduct.html be added with a redirect,  rel=canonical and likely no-index ?

**Comment by joelachance** [comment]
PR https://github.com/numpy/numpy.org/pull/311 resolves this one.

Hugo Aliases: https://gohugo.io/content-management/urls/#aliases

**Comment by rgommers** [comment]
That's a nice and painless way to add redirects:)
