### ISSUE TITLE
ecosystem: feature geoscience (pangeo)

### ISSUE THREAD

**Issue by mdeff** [numpy/numpy.org#319]
Geosciences prominently use data and computations and certainly merits to be featured. The community seems organized under <https://pangeo.io>. I'm however unqualified to pick projects to highlight. There's a list of packages in the [xarray doc](https://xarray.pydata.org/en/latest/related-projects.html#geosciences). Maybe @jhamman or @rabernat can advise.

Or does the fact that these packages mostly use xarray disqualifies them from numpy's landing page?

**Comment by rgommers** [comment]
I'm kind of doubtful about having both "Geographic processing" and "Geosciences", they're quite similar. We have Xarray in the array libraries and GeoPandas, Shapely and Folium in the scientific domains image. I think that's enough coverage, and AFAIK all the packages in that Xarray docs list, with the exception of Open Data Cube, are less prominent than the already features packages.

**Comment by mdeff** [comment]
There's a difference between [geoscience](https://en.wikipedia.org/wiki/Earth_science) (i.e., the study of the physics and chemistry of the Earth system, data not necessarily geospatial) and [GIS](https://en.wikipedia.org/wiki/Geographic_information_system) (i.e., the handling of geospatial data, whether for geoscience, social science, whatever), the current focus of the "Geographic processing" domain.

Whether those can be reasonably merged is beyond my knowledge of those fields. It would be great to have inputs from experts.

Either way, I think pangeo should make it as the federating project for geoscience.

**Comment by rabernat** [comment]
> There's a difference between [geoscience](https://en.wikipedia.org/wiki/Earth_science) (i.e., the study of the physics and chemistry of the Earth system, data not necessarily geospatial) and [GIS](https://en.wikipedia.org/wiki/Geographic_information_system) (i.e., the handling of geospatial data, whether for geoscience, social science, whatever)

:+1:

Some prominent non xarray-based geoscience packages which use NumPy heavily are
- [Simpeg](https://github.com/simpeg/simpeg)
- [ObsPy](https://github.com/obspy/obspy)
- [Fatiando a Terra
](https://github.com/fatiando/)

**Comment by jhamman** [comment]
Just chiming in with a few quick thoughts. I first want to say the new website looks great so nice work to all involved. Also, I know from experience that navigating decisions around which 3rd party projects to highlight can be tricky and is likely to eventually leave someone disappointed. With the possible exception of the packages @rabernat listed, I don't think there is a huge need to pull packages from the xarray ecosystem into this list.

I was personally surprised to not find Xarray in the _Scientific Domains_ or _Data Science_ tabs. If I were to make an unsolicited suggestion on where Xarray could be highlighted in these sections:

- Statistical computing (Scientific Domains
- Extract, Transform, Load or Data Evaluation (Data Science)

Like I said above, balancing content in a section like this is hard so I leave it up to you on whether to take action here.

**Comment by rgommers** [comment]
Sorry for the huge delay. I added a policy/procedure on updating the Ecosystem tab in gh-313. tl;dr we're good to add Geoscience as a category.

We can add up to four projects. Looking at the suggestions here, my order of preference would be:
- Pangeo
- Fatiando a Terra
- Simpeg
- ObsPy

**Comment by rgommers** [comment]
> I was personally surprised to not find Xarray in the _Scientific Domains_ or _Data Science_ tabs. If I were to make an unsolicited suggestion on where Xarray could be highlighted in these sections:

So basically, next to Pandas:) To me under "Statistical computing" makes more sense than in the Data Science tab. The latter tab is really focused on data science as someone with a "data scientist" title in industry dealing mostly with tabular data practices, not the broader "science with data" interpretation.

**Comment by rgommers** [comment]
All suggestions adopted:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/98330/113623162-442faf00-965e-11eb-83f9-a3f0ca02aa9c.png">

Thanks for the input everyone.
