### ISSUE TITLE
ecosystem: merge signal and image processing?

### ISSUE THREAD

**Issue by mdeff** [numpy/numpy.org#321]
I think image processing should be seen as a subset of signal processing ([wikipedia agrees](https://en.wikipedia.org/wiki/Digital_image_processing)). That separation is probably due to signal processing being historically 1D, while we now have nD Euclidean SP and non-Euclidean SP on manifolds/graphs/homogeneous spaces/groups/etc. thanks to [abstract harmonic analysis](https://en.wikipedia.org/wiki/Harmonic_analysis#Abstract_harmonic_analysis) and the underlying [group](https://en.wikipedia.org/wiki/Group_theory) and [representation theory](https://en.wikipedia.org/wiki/Representation_theory). I'll make a PR if people agree.

**Comment by rgommers** [comment]
I'd prefer to keep these separate. xref gh-313 for full update on categories.

> That separation is probably due to signal processing being historically 1D, while we now have nD Euclidean SP and non-Euclidean SP on manifolds/graphs/homogeneous spaces/groups/etc. thanks to [abstract harmonic analysis](https://en.wikipedia.org/wiki/Harmonic_analysis#Abstract_harmonic_analysis) and the underlying [group](https://en.wikipedia.org/wiki/Group_theory) and [representation theory](https://en.wikipedia.org/wiki/Representation_theory)

This is fair from a mathematical point of view, but from a Python users and general scientist background point of view, those are things no one really wants to know about. As you say, the fields are historically separate - and they still are mostly separate for the average user. Plus I want to limit the maintenance work here (e.g., we have new icons for both of these in gh-369 now).

**Comment by mdeff** [comment]
Yeah, it's probably better for categories to follow mainstream usage. Let's hope they merge one day. :)
