### ISSUE TITLE
Announce numpy releases here as well

### ISSUE THREAD

**Issue by mattip** [numpy/numpy.org#322]
We typically announce numpy releases on the scipy.org website, we should do so here as well. xref scipy/scipy.org#349. The News page https://raw.githubusercontent.com/numpy/numpy.org/master/content/en/news.md seems appropriate. We should also announce it on twitter https://twitter.com/numpy_team @charris maybe we should add that to the release process?

**Comment by mattip** [comment]
The [new banner](https://github.com/numpy/numpy.org/blob/b9b283429f3d10254195f1c766982df83adfa957/config.yaml#L34) seems hard-coded to currently display the 1.18 release. When 1.19 is released it should get a mention there for a while: also something for the release process notes?

**Comment by InessaPawson** [comment]
Thank you, @mattip! I was thinking along the same lines and about to email Chuck about it.

**Comment by rgommers** [comment]
Yes, the banner will be updated to `v1.19.0` once the release is made. Release candidates and bugfix releases are not important enough to be on the front page, but they can be on https://numpy.org/news/

**Comment by rgommers** [comment]
and +1 for tweeting

**Comment by InessaPawson** [comment]
> Yes, the banner will be updated to `v1.19.0` once the release is made. 

Let’s clarify which team/who will be in charge of the updates in the news section.

**Comment by rgommers** [comment]
I would suggest this is part of the release process, so @charris can either do it or ping here for the web team to do it. I'm happy to make the updates, but a ping is nice since otherwise I may forgot. @charris is that fine with you?

**Comment by charris** [comment]
Can do. Are you interested in the rc releases or only the stable ones?

**Comment by rgommers** [comment]
> Are you interested in the rc releases or only the stable ones?

Only in the stable releases I'd say. RCs are more a mailing list thing.

**Comment by rgommers** [comment]
This is resolved, so closing. Next update: January for 1.20
