### ISSUE TITLE
Case Study: Diffusion equation solution using numpy/scipy

### ISSUE THREAD

**Issue by tarcisiofischer** [numpy/numpy.org#325]
Hi all.

Just wondering if there is still interest in having my blog post somehow linked in the numpy.org page: https://tarcisiofischer.github.io/1990-01-01/hidden ; As I noticed, there are other posts with direct links on the `learn.md` page.
If yes, please let me know which is better:

a) Just add a link on `learn.md` file directly to my blog post
b) I should add in this repository a new `md` file and copy the contents
c) I should add directly in the numpy repository, as a documentation
d) other

Just mentioning @melissawm, since I've talked to her months ago, but haven't have time to do it (Sorry again).

**Comment by melissawm** [comment]
Just bumping this up, I think it's an interesting case study but perhaps it would be more appropriate in [numpy-tutorials](https://github.com/numpy/numpy-tutorials)

**Comment by rgommers** [comment]
I agree, it's quite a nice tutorial. Having it as a notebook in the `numpy-tutorials` repo would be great. I'd prefer not to link individual blog posts from `learn.md`, that will start to be hard to maintain.

**Comment by rgommers** [comment]
Over at https://github.com/numpy/numpy-tutorialsthings are going well with adding new tutorials, and that's the place to go. So I'll close this issue. Thanks @tarcisiofischer and @melissawm
