### ISSUE TITLE
New Logo Design - Alternative A

### ISSUE THREAD

**Issue by isabela-pf** [numpy/numpy.org#326]
This issue is wrapping up the discussion on NumPy Logo Refresh #37 by providing a place for the community to vote on a logo direction. React with a thumbs up on this issue to vote for this version of the logo (you can vote for multiple). 

Voting closes Friday, June 26. More information on voting expectations can be found [here](https://github.com/numpy/numpy.org/issues/37#issuecomment-645328444).

The other two logo options can be found at #327 and #328 .

![a_fullcolor](https://user-images.githubusercontent.com/50221806/85330638-a467b280-b489-11ea-8e64-7e7390afea32.png)

![a_onecolor](https://user-images.githubusercontent.com/50221806/85330650-a6ca0c80-b489-11ea-80b6-714609cd26e3.png)

<img width="1428" alt="a_websitemockup" src="https://user-images.githubusercontent.com/50221806/85330661-aaf62a00-b489-11ea-9847-bc355501ab04.png">

<img width="1105" alt="a_favicon" src="https://user-images.githubusercontent.com/50221806/85330664-acbfed80-b489-11ea-9499-37b1e2ba4c84.png">

**Comment by charris** [comment]
I do like the suggestion of slab serif.

**Comment by rgommers** [comment]
This is the winner! Voting complete so closing. Thanks @isabela-pf, and everyone who voted and contributed ideas.
