### ISSUE TITLE
New Logo Design - Alternative C

### ISSUE THREAD

**Issue by isabela-pf** [numpy/numpy.org#328]
This issue is wrapping up the discussion on NumPy Logo Refresh #37 by providing a place for the community to vote on a logo direction. React with a thumbs up on this issue to vote for this version of the logo (you can vote for multiple).

Voting closes Friday, June 26. More information on voting expectations can be found [here](https://github.com/numpy/numpy.org/issues/37#issuecomment-645328444).

The other two logo options can be found at #326 and #327 .

![c1_fullcolor](https://user-images.githubusercontent.com/50221806/85331098-5a330100-b48a-11ea-8780-d55fb451f63e.png)

![c1_onecolor](https://user-images.githubusercontent.com/50221806/85331101-5b642e00-b48a-11ea-9894-1c6b054d30c3.png)

<img width="1428" alt="c1_websitemockup" src="https://user-images.githubusercontent.com/50221806/85331105-5d2df180-b48a-11ea-8685-6e03e0a2cfec.png">

<img width="1105" alt="c1_favicon" src="https://user-images.githubusercontent.com/50221806/85331108-5e5f1e80-b48a-11ea-90a1-e53196eee228.png">

**Comment by rgommers** [comment]
Voting complete so closing, thanks everyone! Alternative A in gh-326 is the winner.
