### ISSUE TITLE
Add @rossbar and @bjnath to the Documentation Team 

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy.org#349]
Hi all,

Both @rossbar and @bjnath have been contributing significantly to documentation issues recently, and have been a part of the documentation team meetings, discussions and decision making. I propose to add them to the Documentation Team "grid" in the [team gallery](https://numpy.org/gallery/team.html).

**Comment by rgommers** [comment]
Yes definitely, +1 from me

**Comment by bjnath** [comment]
Thanks, @melissawm and @rgommers!
