### ISSUE TITLE
MAINT: Problem on top of numpy.org pages

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy.org#362]
The navbar formatting is off, and there's stray content at the top of the page:

![image](https://user-images.githubusercontent.com/6691888/94678695-e1dfa580-02ec-11eb-8d3e-6ca61eacc444.png)

Similar issue on the other pages:

![image](https://user-images.githubusercontent.com/6691888/94679010-68948280-02ed-11eb-8ddf-02e84415c496.png)

Seeing this on all browsers (Firefox, Vivaldi, Chrome, Edge).

**Comment by joelachance** [comment]
Seeing the same in Firefox. Looking at it locally things look normal, I'm curious when we built the site last, @rgommers?

**Comment by rgommers** [comment]
Yesterday. Maybe a new Hugo version after a system update. I'm on my other machine now, will check as soon as I can and revert the update.

**Comment by rgommers** [comment]
Okay, should be fixed. Hugo 0.74.3 worked fine, an update to Hugo 0.75.1 broke the navbar somehow. I'll open a new issue for that.
