### ISSUE TITLE
Newer Hugo version introduced rendering issue

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#363]
See gh-362: Hugo 0.74.3 worked fine, 0.75.1 broke the navbar. There's two things to do here:

- Figure out what is broken with the newer Hugo version and fix it.
- Better control the Hugo versions used for Netlify preview and for deployment, so we will not have unexpected breakage when the Hugo version gets bumped through some Linux package manager system update.

EDIT: for completeness, here is the problematic version (on Arch Linux):
```
$ hugo version
Hugo Static Site Generator v0.75.1/extended linux/amd64 BuildDate: unknown
```

**Comment by joelachance** [comment]
It appears this was indeed Hugo. I upgraded this morning to `Hugo Static Site Generator v0.76.2/extended darwin/amd64` and things are working fine. I'm assuming we download the latest Hugo when we deploy, but can't find it in the repo (it doesn't look like it's in the Makefile). I'm not sure how we deploy, but locking it to a version is probably a good idea.

Hope this is helpful, let me know if I can help more with this, @rgommers

**Comment by rgommers** [comment]
Thanks @joelachance, that's helpful!

Deployment is still not automated unfortunately, that's why you can't find it. Issue gh-282 is still open. It's not all that hard, just 1-2 hours of fiddly work.

**Comment by rgommers** [comment]
This was fixed in Hugo a long time ago; gh-422 is upgrading the Hugo version we use from 0.74.3 to 0.82.0. Either way, this issue is already resolved, so closing.
