### ISSUE TITLE
Broken link to PyQuil within Ecosystem section in the main website

### ISSUE THREAD

**Issue by Mandroide** [numpy/numpy.org#367]
Hi, in numpy.org within the Ecosystem section, the link to PyQuil is broken.

**Comment by rgommers** [comment]
thanks for the report. You opened a new issue in the correct repo, so closing this.

**Comment by rgommers** [comment]
Arrh, that wasn't it - "The issue was transferred here" notification was too slow. Reopened.

**Comment by rgommers** [comment]
The thing was moved, new link should be https://github.com/rigetti/pyquil

**Comment by mattip** [comment]
or https://pyquil-docs.rigetti.com/en/stable/
