### ISSUE TITLE
The "Install" page is not responsive?

### ISSUE THREAD

**Issue by AtsushiSakai** [numpy/numpy.org#375]
Hi. First of all, thank you for the new numpy webpage!!. I love it.

When I checked the new numpy webpage from my iPhone, almost pages (front page, Learn, Community, About us, Contribute) looks responsive, but only "Install" page is not responsive. 
Also I cannot scroll the page horizontally and cannot see the right and left side of the page.

And the same thing happens in my second Android phone.
I'm not sure that this is happening in only my phones, let me report it just in case.

This is a screen shot:
![IMG_9255](https://user-images.githubusercontent.com/3813847/103532174-1eafcf80-4ece-11eb-820a-db7905166ce9.PNG)

**Comment by rgommers** [comment]
Thanks for the report @AtsushiSakai. It's the only page with code blocks on it, so that's probably the reason.
