### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by ivirshup** [numpy/numpy.org#383]
Not sure where the best place to report this is, but the docs are down. Currently a 404 https://numpy.org/doc/:

<details>
<summary> 404 </summary>

<img width="607" alt="image" src="https://user-images.githubusercontent.com/8238804/104445980-ea36c480-55ed-11eb-988a-fef36b72bc3c.png">

</details>

Seems like something is going on on `numpy/numpy.github.com` that might be related https://github.com/numpy/numpy.github.com/commit/a88e5f3dddc4bb3872b9be8fd3a50dc71e398bbb?

**Comment by rgommers** [comment]
Thanks. We know, working on it. Please use https://numpy.github.io/doc/ for now.

**Comment by rgommers** [comment]
fixed now

**Comment by ivirshup** [comment]
Great, thanks for letting me know!
