### ISSUE TITLE
Specify the color space in all new NumPy brand identity files

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#386]
@isabela-pf, based on [this discussion](https://github.com/numpy/numpy.org/issues/33#issuecomment-719633348), let's specify the color space, which is sRGB, in all the files with the new NumPy logo.

**Comment by isabela-pf** [comment]
Sounds good! Just to clarify, are you asking me to change the way the SVGs are defined?

**Comment by InessaPawson** [comment]
@isabela-pf Exactly.

**Comment by sm-Fifteen** [comment]
> Sounds good! Just to clarify, are you asking me to change the way the SVGs are defined?

The SVG spec explicitly says that hex color codes (`#CD853F`), the `rgb()` and `rgba()` functions af well as named colors [are all considered sRGB-only color syntaxes](https://www.w3.org/TR/2013/WD-SVG2-20130409/color.html#sRGBcolor) unless a color profile is specified. I was pointing it out more in regards to consistency across SVG, CSS, non-vector images and design documents. The sRGB color profile could probably be explicitly declared on SVG files for good measure, but it really shouldn't be neccessary.

**Comment by InessaPawson** [comment]
> The SVG spec explicitly says that hex color codes (`#CD853F`), the `rgb()` and `rgba()` functions af well as named colors [are all considered sRGB-only color syntaxes](https://www.w3.org/TR/2013/WD-SVG2-20130409/color.html#sRGBcolor) unless a color profile is specified. I was pointing it out more in regards to consistency across SVG, CSS, non-vector images and design documents. 

@sm-Fifteen This is a very helpful clarification. Thank you! I’ll file additional issues.

@MarsBarLee Please remember to specify the color profile (sRGB) in the images you are currently working on.

**Comment by rgommers** [comment]
In gh-404 @isabela-pf says _"I'll go update the logo files and notes on the main NumPy repository as well which should close the issue."_ so I'll reopen this.

**Comment by sm-Fifteen** [comment]
From #404:
> I wasn't totally clear if just changing the way color is defined in the SVG was the goal of the issue since all documentation I found and referenced in the issue said hex color codes and `rgb()` were both considered sRBG. Please let me know if I've misinterpreted this issue and/or if other changes need to be made.

@isabela-pf: You would be right, all these formats are equivalent according to the SVG specification.  Issue #386 was meant to be more about having the brand colors defined in such a way that the intended color can be accurately described regardless of format.

RGB with and without color spaces is a bit like having date-times with and without time zones, where something like "Febuary 23rd, 2021 at 12:05:00" can't be interpreted as a specific, universal moment in time unless the time zone (like "Eastern Standard Time" or "New York time") is also given. sRGB just happens to be the UTC of color spaces, in a way (except unlike with time zones, color space support in software is still only just getting there and most people aren't even aware of them).

I don't believe changing from hex codes to rgb() triplets in the SVG files will have any consequence, given SVG already considers everything to be sRGB by default, but I like decimal RGB triplets, so I'm all for it!
