### ISSUE TITLE
Resizing icons to fit larger screen sizes

### ISSUE THREAD

**Issue by MarsBarLee** [numpy/numpy.org#387]
The current Scientific Domains icons can look too small on larger screen sizes. This is because the icons are a fixed size, around 120px by 120px, As they currently in the PNG format, scaling them up would cause artifacts and blurriness.

I'm currently working on another issue to replace the icons with SVGs (which would scale at larger sizes without problem), so I'll come back to this issue once that's done.

This fix would be a part of responsive web design and accessibility.

**Comment by InessaPawson** [comment]
@MarsBarLee I'm closing this issue as it was addressed by https://github.com/numpy/numpy.org/pull/403.
