### ISSUE TITLE
Page width issue

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#395]
After updating to deployment with the GitHub Action, it looks like there's an issue with page widths - there's a scroll bar at the bottom of every page:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/98330/106944184-93249b00-6726-11eb-9f84-a7559065f30e.png">

I checked if this could be due to the Hugo version used,seems unlikely, it's 0.74.3 in the Action now and I can reproduce it with v0.80.0 locally. 

Not sure what's going on there. @joelachance any idea?

**Comment by joelachance** [comment]
I don't have any idea, this seems pretty weird! I'll look into it, likely this weekend or next week @rgommers
