### ISSUE TITLE
Website Content

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#40]
We're missing some stuff (mostly cool looking images), but copy too. Continue working on this.

New content lives on the branch `newsite` (branched from master of numpy.org), in the directory `/new-content`. We can add and commit updated content there for the time being.

**Comment by stefanv** [comment]
Is this the appropriate issue for discussing the front page?

The front page is arguably the most important part of the site, since it has to capture users and focus their attention to deeper within the website.  It took a look at the current mock-up.  It is beautiful, but I feel it goes too far in the simplicity direction: i.e., while it succeeds in not being visually overwhelming, it misses an opportunity to convey some useful information in that prime space.

See, e.g., the [Haskell website](https://www.haskell.org/).  It immediately shows you interesting parts of the project, in this case even allowing you to play with some elements of it.  Somewhat similar for [nim](https://nim-lang.org/features.html).

We have a beautiful API, so maybe we can showcase it?

**Comment by joelachance** [comment]
I really like the Haskell website. I think the interactive command shell quite a bit, and it's a little bit addicting. I now know more Haskell than I did 5 minutes ago :) 

That being said, I think that will likely take some time if people are interested in that (I think it would be a great addition). However, I do think we could easily implement something static that will give the same message. Any suggestions for content?

**Comment by stefanv** [comment]
The interactive session is fun, but probably a stretch for us to build.  I more wanted to focus on the code snippets and the value they could add.

(That said, an interactive component could be [backed by AWS Lambda quite easily](https://medium.com/@korniichuk/lambda-with-pandas-fd81aa2ff25e).)

**Comment by joelachance** [comment]
So Haskell (and others) are using this library: https://github.com/chrisdone/jquery-console
I think we can do this easier than I was expecting, but probably not priority #1.

If anyone has an impressive code snippet you'd prefer we use, I can add that for now.

**Comment by stefanv** [comment]
Maybe something like:

```python
import numpy as np

x = np.linspace(-1, 1, 1000)
y = x[..., np.newaxis]
z = np.sin(x**2 + y)

p0 = np.sum(z, axis=0)
p1 = np.sum(z, axis=1)
```

And then display something like a [marginal plot]:

![image](https://user-images.githubusercontent.com/45071/65471244-60288280-de23-11e9-9908-b32d6dc30c02.png)

Instead of histograms, showing p0 and p1.

If that code snippet is too complicated, something like:

```
# Pure Python

N = 10000 
samples = [s/N for s in range(0, N)] 
squared = [s**2 for s in samples] 

# NumPy: simpler notation, and much faster
samples = np.linspace(0, 1, N) 
squared = samples**2 
```

**Comment by rgommers** [comment]
Good point, a code snippet would be great. I like that hexbin plot code better. Showing that plot without the code for it is a nice idea. Could you add the code here @stefanv so it can be tweaked (e.g. green needs change to our color scheme)?

**Comment by rgommers** [comment]
> (That said, an interactive component could be [backed by AWS Lambda quite easily](https://medium.com/@korniichuk/lambda-with-pandas-fd81aa2ff25e).)

> So Haskell (and others) are using this library: https://github.com/chrisdone/jquery-console
> I think we can do this easier than I was expecting, but probably not priority #1.

Single expressions are doable it seems, but an actual shell is much harder probably. If it's responsive and backed by AWS Lambda it would be cool indeed ....

**Comment by mattip** [comment]
Running an interpreter instance on a server via javascript can open up security problems and resource abuse. Solutions such as the [PyPy sandbox](http://doc.pypy.org/en/latest/sandbox.html) which recently got and update exist, but are not trivial. We could consider running something like [pyiodide](https://alpha.iodide.io/notebooks/300/) which runs in the user's browser, but I don't think that should be our first priority.

**Comment by stefanv** [comment]
> Good point, a code snippet would be great. I like that hexbin plot code better. Showing that plot without the code for it is a nice idea. Could you add the code here @stefanv so it can be tweaked (e.g. green needs change to our color scheme)?

The hexbin was just an example, taken from the [seaborn gallery](https://seaborn.pydata.org/examples/hexbin_marginals.html).  It doesn't illustrate NumPy very much.

**Comment by joelachance** [comment]
> Running an interpreter instance on a server via javascript can open up security problems and resource abuse. Solutions such as the PyPy sandbox which recently got and update exist, but are not trivial. We could consider running something like pyiodide which runs in the user's browser, but I don't think that should be our first priority.

100%. However, I am interested in solving this problem. I think this would be really great to have either on the site, or standalone (or both).

I think I may reach out to the person who did Haskell's sandbox and see what he has to say. Looking at what code I can in the browser, I have a feeling their implementation might not be very secure.

Regardless, not our first priority :)

**Comment by rgommers** [comment]
Cool, be curious to hear what you learn @joelachance.

**Comment by stefanv** [comment]
> 100%. However, I am interested in solving this problem. I think this would be really great to have either on the site, or standalone (or both).

AWS lambda now has a layer with NumPy and SciPy included:

https://aws.amazon.com/blogs/aws/new-for-aws-lambda-use-any-programming-language-and-share-common-components/

Our system could be as simple as CodeMirror -> send code to lambda -> display resulting object.  AWS will allow us to set very clear resource limits, and we can switch networking off so that no remote data can be fetched.  We can also have the call timeout in 5 seconds or so.

**Comment by stefanv** [comment]
@joelachance I spoke to Chris Holdgraf this morning and turns out this can be done trivially using ThebeLab + MyBinder: https://thebelab.readthedocs.io/en/latest/

Only downside is that it takes a few seconds for the kernel to spin up, but subsequent commands execute quickly.

If we have some money, we could also host our own binder instance, which would make startup very quick (we can pre-pull the image we are interested in, which currently is what causes the delay).

**Comment by joelachance** [comment]
I will look into this! I never heard back from Chris Done who did the Haskell sandbox. I may try him at Twitter next...

**Comment by stefanv** [comment]
If you get stuck, you can get in touch with @choldgraf, who also uses this for Jupyter Book.

**Comment by choldgraf** [comment]
Note that if you ran your own Binder instance, you could also request the kernel upon *page load* instead of waiting for someone to click a button before requesting the kernel. It's all a question of resource management and cost :-)

**Comment by joelachance** [comment]
@choldgraf, good to know! I'm going to look at this this coming week, I may be in touch with questions :)

**Comment by InessaPawson** [comment]
> The front page is arguably the most important part of the site, since it has to capture users and focus their attention to deeper within the website. It took a look at the current mock-up. It is beautiful, but I feel it goes too far in the simplicity direction: i.e., while it succeeds in not being visually overwhelming, it misses an opportunity to convey some useful information in that prime space.
> 
> See, e.g., the [Haskell website](https://www.haskell.org/). It immediately shows you interesting parts of the project, in this case even allowing you to play with some elements of it. Somewhat similar for [nim](https://nim-lang.org/features.html).
> 
> We have a beautiful API, so maybe we can showcase it?

@stefanv The website content is still at the stage of brainstorming. Excellent timing on your idea for the front page!

**Comment by charris** [comment]
```
        # Map centroids to ideal camera FPA and turn them into 3-D
        # direction vectors
        pts[..., :2] = self.fpamap(self.centroids, parm, desc)
        pts[..., 2] = 1.0
        pts /= np.sqrt(np.sum(pts * pts, axis=-1, keepdims=True))

        # Compute correlation matrices for all patches.  The result has
        # dimensions (n, 3, 3).
        wpts = pts * weight
        cor = np.einsum('kij, kim -> kjm', pin, wpts, out=self.cor)

        # Compute matching rotations using the singular value method.
        # Requires numpy >= 1.8 for stacked svd. The output has dimensions
        # (n, 3, 3).
        u, d, v = np.linalg.svd(cor)
        rot = np.einsum('ijk, ikl -> ijl', u, v, out=self.rot)
```

**Comment by erfannariman** [comment]
One of the most impressive numpy usage I've seen are from [this](https://stackoverflow.com/users/3293881/divakar) user on SO. Definitely worth to check his answers.

**Comment by joelachance** [comment]
@choldgraf I have binder working and a NumPy shell working in the browser. Splitting this out into another ticket (#66). Thank you for the suggestion, it's working well!

**Comment by rgommers** [comment]
Okay this is all done and can be closed. The shell content in this issue is superseded by gh-81. Thanks everyone for the input!
