### ISSUE TITLE
Link to official numpy documentation is hard to spot

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy.org#400]
I completely missed that the word "here" was a link on [this page](https://numpy.org/learn/), possibly due to a blue-light filter.
The fact that it appears in bold right at the top of the page furthers the confusion, suggesting that that page itself _is_ the official documentation!

Note that the image below is much clearer on my screen than the actual page is, as chrome uses a different color profile for PNG images than it does for text colors!

![image](https://user-images.githubusercontent.com/425260/107976516-9a169d80-6fb1-11eb-93e2-26d577714905.png)

**Comment by InessaPawson** [comment]
@eric-wieser One possible solution could be replacing the word **here** with the address of the NumPy docs: **https://numpy.org/doc/stable**. 

Wrt difference in color profiles, we are aware of the issue (#399, #398, #397).

**Comment by eric-wieser** [comment]
The color profile issue is really just me complaining about github, but I'm glad its also on your radar for the website!

Changing the link text to a url would help. Maybe a "visit the official documentation" button would work too. I don't feel strongly, just thought I should record my confusion somewhere.

Looking at this again in the morning, the problem is definitely largely brought on my an extreme blue-light filter I had enabled in the evening.

**Comment by melissawm** [comment]
In any case, for accessibility, it would be nicer to rephrase that to something like:
```
You can find the official NumPy documentation by [clicking here](link).
```

**Comment by InessaPawson** [comment]
How about the following phrasing:

For the **official NumPy documentation** visit [numpy.org/doc/stable](https://numpy.org/doc/stable).
