### ISSUE TITLE
Installation guide installs incorrect packages on ARM based CPUs

### ISSUE THREAD

**Issue by millettmb** [numpy/numpy.org#401]
Hi all,
I found out today that performing `pip3 install numpy` on an ARM based CPU procures an incorrect version of the LAPACK library (?). This doesn't present as an error, but instead results in incorrect values produced from some of the functions within the `numpy` library, such as `linalg.eigvals`. More information is available in the issue here: https://github.com/numpy/numpy/issues/18422.

I believe that the installation page, listed here: https://numpy.org/install/, should be modified to include information about ARM specific installations, and/or provide a link to the AWS provided documentation on how to properly install `numpy` on ARM based CPUs (https://github.com/aws/aws-graviton-getting-started/blob/master/python.md).

**Comment by mattip** [comment]
Maybe there is a problem with your procedure? We ship OpenBLAS with our wheels, and if the version of OpenBLAS is wrong it is a numpy/numpy problem, not a documentation one. The page you link to says "As of June 20th, 2020, NumPy now provides binaries for arm64." so maybe that page should remove the whole "build from source" portion.

**Comment by rgommers** [comment]
Graviton is not a regular ARM64 architecture, it's a custom chip from Amazon that AFAIK is only available on AWS. This issue belongs on the main repo I think, not here. So I'll close this and will comment on as well.
