### ISSUE TITLE
How do I reference the 'numpy' library

### ISSUE THREAD

**Issue by zhaocheng-hub** [numpy/numpy.org#406]
Hello, I have used some methods of 'numpy' library in my academic paper. How should I quote them in my paper?

**Comment by InessaPawson** [comment]
> > Or as a quick access in the footer?
> 
> +1

I'll add a link in the footer.

**Comment by zhaocheng-hub** [comment]
Thank you

**Comment by InessaPawson** [comment]
> .... at least I should have tried `site:numpy.org citing` which points out the "citing" page

It’s the top search on every search engine I could think of even if you don’t specify the website.;)
