### ISSUE TITLE
Build tabbed content similar to https://julialang.org.

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#41]
Per Ralf's suggestion in the content files, we should add custom tabbed content similar to Julia's site. This isn't included in our Hugo template, so we'll need to build it out.

**Comment by joelachance** [comment]
Julia is using: https://github.com/CodyHouse/responsive-tabbed-navigation

This as been added to `newsite`. Adding content, testing, then closing.

**Comment by rgommers** [comment]
Just showed the current state of `newsite` to a few people in the NumPy community call, just to give everyone a sense of the new style of the design. Overall feedback was very positive.

**Comment by joelachance** [comment]
@rgommers Can we close this one? Or would you like to discuss tab content here?

**Comment by rgommers** [comment]
yep let's close it, thanks @joelachance
