### ISSUE TITLE
Chemistry packages in Ecosystem tab

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#411]
I'm replacing PyChem (unmaintained) with Cantera, which is a large, NumFOCUS-sponsored project and should definitely be there. Not sure what are the other popular chemistry Python packages though. 

From a browse through https://github.com/lmmentel/awesome-python-chemistry, `stk`, `mendeleev` and `ionize` all look decent. I'd like to take the best (actively maintained, widely used, depending on numpy, high quality) 3-4 projects though, not just my impression from a quick browse.

@bryanwweber would you be able to make a recommendation here?

**Comment by shoyer** [comment]
Two projects that come to mind for me:
- [RDKit](https://github.com/rdkit/rdkit) -- very popular for chem-informatics
- [MDAnalysis](https://github.com/MDAnalysis/mdanalysis) -- NumFOCUS sponsored

**Comment by rgommers** [comment]
Thanks @shoyer, adopted.

We have space for one more if there's another chemistry package of similar size/importance.

**Comment by bryanwweber** [comment]
Hi @rgommers I'd be happy for Cantera to be included here. Let me know if there's anything I can do to help.

**Comment by rgommers** [comment]
Hey Brian, it's done already: 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/98330/113715531-e3e64f00-96e9-11eb-85a5-e4692d3de8be.png">

If there's another important Python chemistry project we missed, please let us know. Otherwise we're all set here.

**Comment by bryanwweber** [comment]
Thanks @rgommers!!
