### ISSUE TITLE
Padding for translated text in top-page cards 

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy.org#417]
Similar to #416: translated (portuguese) text in the cards takes up more space than expected. Row 1, column 2 shows the text too close to the bottom border:

![Screenshot_20210419_182250](https://user-images.githubusercontent.com/3949932/115305339-8831b200-a13c-11eb-8813-e3a5a801aaf5.png)

Not sure if this will happen for other languages, though.

**Comment by rgommers** [comment]
I'm not sure if there's a better solution than "use as much whitespace as the most verbose language needs". @joelachance any other ideas?

**Comment by joelachance** [comment]
`text-overflow: ellipsis;` looks like a pretty cool solution that might be a good option here, I can look at this if needed. Let me know, @rgommers!

More examples/info here: https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by rgommers** [comment]
Great idea @joelachance! I think for box titles it may look a little odd and we should increase the space a bit to make things fit (if every 3-4 word title has the last word replaced by `...` that probably loses too much), but for text that's 3-4 lines long it should work well. There's more multi-line examples at https://css-tricks.com/line-clampin/. The "fade out way" looks nice too.

**Comment by joelachance** [comment]
@rgommers, I agree about the titles, we should definitely increase padding/margin there. I also like the fade out for the main content in these cells, good find!
I can work on this one.

**Comment by rgommers** [comment]
Thanks!

**Comment by joelachance** [comment]
How does this look? I didn't add much to the title, but I think it looks a little better. I did check it on English and it seems fine, I didn't check it on other translations yet besides en and pt.

Fade added, see column 2, row 1.

<img width="1222" alt="Screen Shot 2021-05-02 at 10 01 27 PM" src="https://user-images.githubusercontent.com/3891660/116837923-f8efba00-ab91-11eb-83e1-771cb2c7a788.png">

**Comment by rgommers** [comment]
Looks good to me! @melissawm what do you think?

PR preview will show en/pt/ja so it'll be easy to compare.

**Comment by joelachance** [comment]
PR above!
@rgommers  @melissawm

**Comment by melissawm** [comment]
Left my review in the PR - looks great to me, thanks!
