### ISSUE TITLE
Add community calendar to the Community section

### ISSUE THREAD

**Issue by isabela-pf** [numpy/numpy.org#436]
### What I'd like
A calendar that lists all upcoming NumPy community events on the Community section. I think this could easily be added as a new entry under the Participate Online section. I would find it most helpful if this was truly on a calendar where I could see the upcoming dates, but at the very least I would be happy to have a list of events that happen on a regular basis so I know what I am looking for on the mailing list.

For example, the calendar I use regularly in Jupyter looks like this: https://jupyter.readthedocs.io/en/latest/community/content-community.html#jupyter-community-meetings

### Why I think it would be helpful
I've been starting to go to NumPy documentation meetings lately and often find myself getting confused if it is a week that the meeting is happening or one of the off weeks. Since multiple NumPy community meetings happen at a less-than-weekly cadence, I think it is likely I'm not the only one who loses count of the weeks sometimes. 

This would also make it easier to have a central place to point people to all meetings instead of having to keep a constant eye on the mailing list for the reminders there (what I currently do).

Thanks for considering this! I'm a little strapped for time right now, but if there is a way I can support this happening please let me know.

**Comment by rgommers** [comment]
This may be a good idea, thanks for the suggestion @isabela-pf. 

My main question is: how do we deal with a safety issue like "Zoom bombing"? Right now you can find the meeting invites, and they get shared on the mailing list and our ask-for-an-invite-first Slack instance. So anyone in the world can already join, but it takes some work. If we make it easy to find on a website that gets a couple of million of visitors a month, it seems to me that the risk goes up quite a bit. Maybe that's okay and part of life as an open community, I really don't know. Would be good to search for experiences/guidance from other communities.

**Comment by melissawm** [comment]
I share that concern. In the events I'm creating I'm enabling the waiting room and muting of participants by default when they join, but I've never faced problems so it's hard to tell how it would be if we did have problems.

**Comment by seberg** [comment]
We now already have one here: https://scientific-python.org/calendars/ but it may be nice to link to that website from our community site?

**Comment by BhaswatiRoy** [comment]
Hello
The link to the calendar can be added under "join the numpy community" section.
![image](https://user-images.githubusercontent.com/78029145/212463827-efb1aca4-30fd-4f43-8fda-092347921ff8.png)
I can work on this!

**Comment by InessaPawson** [comment]
@BhaswatiRoy, that would be great!

**Comment by BhaswatiRoy** [comment]
Hello @InessaPawson 
It would be great if you could assign this issue to me!
Thanks

**Comment by InessaPawson** [comment]
@BhaswatiRoy NumPy doesn't assign issues. To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

**Comment by BhaswatiRoy** [comment]
Hello @InessaPawson 
Thanks for letting me know!
I have submitted a PR, do please let me know if I have to make any changes!
