### ISSUE TITLE
Webpage listing downstream array libraries

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy.org#44]
It would be useful to have a page on the NumPy or SciPy website listing downstream array libraries and what features they provide briefly. Pandas undertook a similar effort recently and created [this page]( https://pandas.pydata.org/pandas-docs/stable/ecosystem.html ). In particular the [out-of-core section]( https://pandas.pydata.org/pandas-docs/stable/ecosystem.html#out-of-core ) seems similar to the idea presented here.

cc @mattip (as we discussed this briefly at EuroSciPy)

**Comment by rgommers** [comment]
Thanks @jakirkham. A whole new website is in the works (in this repo), and your proposal is on my radar. If you'd want to write some content or even just start a list of libraries to include in this issue, that would be very welcome.

**Comment by jakirkham** [comment]
Cool, thanks Ralf! Sorry for opening this on the wrong repo to start.

**Comment by rgommers** [comment]
No worries. Gave me the chance to try out this newfangled "transfer issue" feature - I like it:)

**Comment by rgommers** [comment]
Current status of master:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/98330/71769944-44a33c80-2f27-11ea-8c00-5d8a02ddcf9b.png">

**Comment by rgommers** [comment]
The array computing page and this tab are one of the last ones still needing review - should be done by the end of the weekend.

**Comment by rgommers** [comment]
Calling this good for now, after gh-268. More after launch once we bring back the updated content of "array computing".
