### ISSUE TITLE
Update Install page to always recommend conda-forge

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#442]
`defaults` right now still have numpy 1.19.2 as the latest NumPy version, which means it's outdated by about 8 months and 7 releases (1.19.3-1.19.5, 1.20.0-1.20.3). The situation is no better with other important packages, and it's getting a bit ridiculous. `conda-forge` on the other hand is maintained very well, and has only gotten better / more stable since the last update to our Install page. So let's simplify the advice and just always recommend conda-forge.

Also recommend Mambaforge as the preferred installer.

**Comment by InessaPawson** [comment]
@rgommers Please let us know if you are still planning to work on this issue.
P.S. `defaults` currently installs NumPy 1.26.4 (the latest version as of now), not sure about the other packages.

**Comment by rgommers** [comment]
This page has changed a bit since this issue was opened ~3 years ago. I don't plan to work on this any time soon. So let's close the issue.
