### ISSUE TITLE
Update the README.md file. (Add extra prerequisites to download MinGW)

### ISSUE THREAD

**Issue by Uttam-Singhh** [numpy/numpy.org#445]
In the Readme file, It is mentioned that you only need to install `HUGO`. 
but when the developer will move forward he/she will have to run `make hugo` and `make` command is not supported by Windows(No idea of other operating systems).

So, there should be an extra dependency to download [MinGW - Minimalist GNU for Windows](https://sourceforge.net/projects/mingw/).
or they follow [this](https://www.youtube.com/watch?v=taCJhnBXG_w) video.

**Comment by mattip** [comment]
... or document that on windows you should do (not tested, should work)
```
python gen_config.py
hugo -b        
```

**Comment by rgommers** [comment]
Thanks for the report @Uttam-Singhh. I agree with @mattip's suggestion - all the `make hugo` does extra is running `python gen_config.py`. So let's recommend that instead, MinGW is too complicated. A PR for clarifying the README would be great.

**Comment by Uttam-Singhh** [comment]
Done! @rgommers
Please Let me know if there is an issue!
