### ISSUE TITLE
Idea #1 for Team page

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#45]
This is generated from a simple yaml file that then fetches data from GitHub and creates a gallery: https://datapythonista.github.io/pandas-web/community/team.html

Code at https://github.com/datapythonista/pandas-web/blob/master/pysuerga.py#L43
Thanks for the suggestion, @datapythonista!

**Comment by datapythonista** [comment]
The code has now been committed to pandas, the new links are:
- https://dev.pandas.io/community/team.html
- https://github.com/pandas-dev/pandas/blob/master/web/pandas_web.py

If you can be interested in the whole `pandas_web.py` script, I'm happy to move it to a separate repo and create a conda package for it. Probably after we integrate the new website with Sphinx. Since we'll need to render the naviagation bar from the yaml in Sphinx too.

**Comment by InessaPawson** [comment]
Very nice, @datapythonista! 
The new active link is dev.pandas.io/about/team.html

**Comment by shaloo** [comment]
> This is generated from a simple yaml file that then fetches data from GitHub nad creates a gallery: https://datapythonista.github.io/pandas-web/community/team.html
> 
> Code at https://github.com/datapythonista/pandas-web/blob/master/pysuerga.py#L43
> Thanks for the suggestion @datapythonista

Hi, the first link team.html is not working.  @datapythonista, @rgommers is this information available somewhere else?  I checked datapythonista.me domain as well but couldn't locate it.

**Comment by datapythonista** [comment]
Sorry @shaloo, those pages were deployed, and I removed my temporary copy.

- https://datapythonista.github.io/pandas-web/community/team.html -> https://pandas.io/about/team.html
- https://github.com/datapythonista/pandas-web/blob/master/pysuerga.py -> https://github.com/pandas-dev/pandas/blob/master/web/pandas_web.py

**Comment by shaloo** [comment]
@datapythonista, thanks - it looks v v nice!

**Comment by shaloo** [comment]
Taking this up over the weekend...thx!

**Comment by rgommers** [comment]
Thinking about who to list. Some thoughts:
- I like the Pandas ordering: Contributors, then Maintainers, then other teams.
- We have a Steering Council which Pandas doesn't have; I think that is less important Maintainers, so let's just list those towards the end under Governance.
- I'd be inclined to do it like Pandas and put active Maintainers in the gallery, and use Emeritus Maintainers for people no longer active.
- I'd like to add other teams/roles here. We haven't formalized that yet, but at least we can list Web and Documentation teams. Maybe leave other things like industry contacts and fundraising for later once we've sorted that out.

Does that sound okay to everyone?

**Comment by rgommers** [comment]
@shaloo would it be easy to have separate galleries for Web and Documentation teams?

**Comment by stefanv** [comment]
> Thinking about who to list. Some thoughts:
> 
>     * I like the Pandas ordering: Contributors, then Maintainers, then other teams.
> 

I was surprised when I read this at first, so to clarify for others who may also read this incorrectly: Pandas does not list all contributors first, they are mentioned as a group ("1500 contributors"). Maintainers are then listed, individually, with photos.

**Comment by shaloo** [comment]
> @shaloo would it be easy to have separate galleries for Web and Documentation teams?

Yes, we can do that.

**Comment by shaloo** [comment]
> Thinking about who to list. Some thoughts:
> 
> * I like the Pandas ordering: Contributors, then Maintainers, then other teams.
> * We have a Steering Council which Pandas doesn't have; I think that is less important Maintainers, so let's just list those towards the end under Governance.
> * I'd be inclined to do it like Pandas and put active Maintainers in the gallery, and use Emeritus Maintainers for people no longer active.
> * I'd like to add other teams/roles here. We haven't formalized that yet, but at least we can list Web and Documentation teams. Maybe leave other things like industry contacts and fundraising for later once we've sorted that out.
> 
> Does that sound okay to everyone?

Ok can be done provided I have a list of who’s who. At present I simply fetched top 18 contributors from Github in order to try out @datapythonista suggestion above.

**Comment by InessaPawson** [comment]
> I'd like to add other teams/roles here. We haven't formalized that yet, but at least we can list Web and Documentation teams. Maybe leave other things like industry contacts and fundraising for later once we've sorted that out.
> 
AstroPy has done a good job on outlining roles and responsibilities within the project.
(See here: https://www.astropy.org/team.html) I’m not sure if we are there yet with the headcount.

**Comment by rgommers** [comment]
> AstroPy has done a good job on outlining roles and responsibilities within the project.
> (See here: https://www.astropy.org/team.html) I’m not sure if we are there yet with the headcount.

That's indeed quite nice. We're definitely not there yet. Would like to get there at some point though - maybe approaching that level of role clarity by the end of the year.

**Comment by rgommers** [comment]
Putting together the names for this page was a little challenging, and because we don't have formal teams and roles yet, here is my best attempt:

```
## Maintainers

- ahaldane
- mhvk
- shoyer
- njsmith
- rkern
- eric-wieser
- stefanv
- pv
- rgommers
- charris
- seberg
- juliantaylor
- bashtage
- matthew-brett
- WarrenWeckesser
- mattip
- tylerjereddy


## Web team

- joelachance
- InessaPawson
- MarsBarLee
- shaloo
- rgommers


## Documentation team

- melissawm
- rgommers
- bonn0062


## Emeritus maintainers

- Travis Oliphant
- David Cournapeau
- Mark Wiebe
- Jaime Fernández del Río
- Alex Griffing
- Ondrej Certik
- Jonathan Helmus
- Francesc Alted

## Governance

For the list of people on the Steering Council, please see [here](https://numpy.org/devdocs/dev/governance/people.html)
```

It also highlighted again that we have multiple people with commit rights who haven't contributed in years, I'm inclined to clean that up. I listed here only _active_ maintainers and web/docs team members. I also judged "maintainers" to be the key code-related group, and "steering council" much less important. @numpy/numpy-core-team comments very welcome.

**Comment by shoyer** [comment]
@rgommers Thanks Ralf, this looks great to me.

**Comment by shaloo** [comment]
Early draft of team.html page based on grouping suggested above:

<img width="679" alt="Screenshot 2020-03-23 at 6 28 58 PM" src="https://user-images.githubusercontent.com/5890484/77319128-4a453d00-6d34-11ea-8ee0-d5381a227708.png">

<img width="685" alt="Screenshot 2020-03-23 at 6 29 12 PM" src="https://user-images.githubusercontent.com/5890484/77319179-5fba6700-6d34-11ea-8d1e-105d337323f0.png">

<img width="686" alt="Screenshot 2020-03-23 at 6 29 20 PM" src="https://user-images.githubusercontent.com/5890484/77319197-65b04800-6d34-11ea-9923-58ffacbbfa45.png">
<img width="722" alt="Screenshot 2020-03-23 at 6 29 29 PM" src="https://user-images.githubusercontent.com/5890484/77319210-6a74fc00-6d34-11ea-9e70-5a94cf290158.png">

**Comment by shaloo** [comment]
Regarding integrating this script, here are some initial thoughts.  Let me know if you have other/better ideas:

* Typically, team list is static so it does not make sense to generate this page at every hugo build.
* The script uses GitHub http request to obtain details (avatar, id, etc) of team members. Github requests are limited and cannot be done more than x number per day. So the script has an option to use stored data (from GitHub) and then rerun it for changing layouts and number of profiles shown in a row etc. This ensures you can run it once and fetch data from GitHub and laters use stored data for relaying out content.  Again, this relayout frequency will be low ( I am guessing) assuming team changes are not frequent.

**Comment by charris** [comment]
> Putting together the names for this page 

We should give Anne Archibald an emeritus entry, she had commit rights when we were on svn that got lost in the move to github because she had moved on.

**Comment by rgommers** [comment]
Looks great @shaloo!

Thanks @charris, good point about Anne. @shaloo could you add her? I was actually thinking to have the emeritus maintainers just as a list of names, not a gallery (rationale: they're gone, so de-emphesize a little).

 
> Typically, team list is static so it does not make sense to generate this page at every hugo build.

Agreed, your approach sounds good.

> Alternative integration is to embed this script generated gallery html into Team.md page using raw html shortcodes.

I suspect that this will be nicer than another separate page.

**Comment by charris** [comment]
And Alex Griffin had the cool snail avatar. See https://github.com/argriffing @argriffing. He disappeared so suddenly and completely that I worry.

**Comment by charris** [comment]
Anne is @aarchiba on github.

**Comment by charris** [comment]
> I was actually thinking to have the emeritus maintainers just as a list of names,

I kind of like the gallery.

**Comment by stefanv** [comment]
@rgommers I'm not sure about the list of emeritus maintainers. Several of these folks do not seem to qualify, but it could be that I missed substantial contributions from them. What is the rule for inclusion here?

I also notice that @jarrodmillman is not listed, who managed 5+ releases and coordinated several important community meetings.

**Comment by rgommers** [comment]
Thanks @stefanv, good catch - added Jarrod. And valid point on criterion.

The ones you mean are probably Alex Griffing, Ondrej Certik, Jonathan Helmus and Francesc Alted. They all have commit rights, and were part of the NumPy team at some point. I agree that their contributions are all fairly marginal to be considered for this list. Happy to remove them all, seems fair indeed - there are many other people with similar amounts of contributions.

If we disregard commit rights yes/no, then I'd draw the line at Jarrod and Jaime. Okay, removing them.

**Comment by rgommers** [comment]
> They all have commit rights,

fixed that too - they no longer have commit rights

**Comment by certik** [comment]
For the record, my contribution was that I put in many months of work to get NumPy 1.7 out and was the release manager for it. It didn't translate to a lot of commits, but it took a lot of time to figure out how to fix things and how to get everything working on all platforms and how to coordinate with all the contributors.

**Comment by rgommers** [comment]
@certik thanks for pointing that out. Yes I definitely remember you did 1.7.0/1! It was even longer than I remembered (Jul-Apr), and one of the more painful releases in NumPy's history. I think your contributions were more substantial than the others mentioned above. There's also still a bit of a gap with Jarrod/Jaime, who contributed for 3 or more years - let me confer with @stefanv on this list.

**Comment by rgommers** [comment]
Oops, somehow also forgot Pearu - added.

**Comment by certik** [comment]
@rgommers indeed, it was a lot of work, over a long period of time at a point when nobody wanted to do this job for NumPy. Whether that meets the bar for this issue is up to you. But I just wanted to set the record straight regarding my contributions to NumPy.

**Comment by charris** [comment]
Having too many emeritus contributors is not a problem we should worry about, having too few is more likely to ruffle someone's feathers.

**Comment by shaloo** [comment]
Taking into account suggestions above, here is the second draft.  
<img width="1011" alt="Screenshot 2020-03-24 at 4 24 47 PM" src="https://user-images.githubusercontent.com/5890484/77418374-ce5afb80-6dec-11ea-9e2c-28e24ac93236.png">
![Uploading Screenshot 2020-03-24 at 4.25.02 PM.png…]()

**Comment by rgommers** [comment]
Thanks for the input everyone, and the new draft @shaloo.

First off all, someone pointed out to me this phrasing didn't sound right: _"fairly marginal to be considered for this list"_. I apologize if that came over wrong - I definitely did not mean to under-appreciate anyone's efforts! What I meant was that what I (and I think also @stefanv) had in mind for "emeritus maintainer" status was people who were part of the NumPy core team long term, typically multi-year sustained contributions. We have many many other people who made lots of valuable contributions over the years.

Drawing a line somewhere is hard. @InessaPawson had the very nice suggestion to (on a separate page) list _all_ contributors by name. This sounds like a good idea to me. We can use a script for that and the `.mailmap` file in the main repo which is reasonably well-maintained because we use it for a similar purpose of listing names of contributors in the release notes.

@shaloo could you make a PR with what you have? And can you add @certik back to that? I may have forgotten a couple of other people, I will go back and double-check everything.

**Comment by shaloo** [comment]
ok. Will do that in the next couple of hours.

**Comment by shaloo** [comment]
Done. Pls review.

* Original Team.md generated html was linked in about page - so about page is now updated to refer to gallery team page generated using this script and stored under static/gallery area - recommended by Hugo devs (to include html).

*Original Team.md page was redundant (checked, not referred to from anywhere else), so deleting it from content/en/team.md  This page has a new avatar in scripts/gallery/numpy/team.md and that is used to generate gallery/team.html.

**Comment by rgommers** [comment]
> recommended by Hugo devs (to include html).

Can you expand on this? It seems weird to me, since regenerating the html is very cheap. Only retrieving data from the GitHub API should be cached I'd think.

**Comment by shaloo** [comment]
Yes generating html is cheap and fast if you use stored content.  What I meant by above is, in hugo forum I came across a conversation where folks were looking for a way to incorporate statically generated html files as part of their hugo site content and the response was to add the html file in static area and refer to it elsewhere in Hugo content.  As of now, I have taken the same approach.

**Comment by rgommers** [comment]
Okay, I think that discussion may have been about some externally-generated html then. In this case I don't see why we would treat the Team page different from the other pages - it's all html pages generated by Hugo itself.

**Comment by shaloo** [comment]
> Okay, I think that discussion may have been about some externally-generated html then. In this case I don't see why we would treat the Team page different from the other pages - it's all html pages generated by Hugo itself.

I think I am missing something that you are suggesting here.  Afaik, the static html page is generated by script and then plugged in hugo - so it is external in that sense.  Who runs the script and when?  It is run once and not at every Hugo build.  So this team html page is like a png (sort of) for hugo.  What am I missing?

**Comment by rgommers** [comment]
Ah I see the confusion. The last part of the script does use jinja2, I missed that. It does very little though. For each gallery all it does is a for-loop over the entries in `team.context`, and then inserts the same `<div class="card rounded"> ... ` card. I think it'd be much cleaner to do that with Hugo itself: https://gohugo.io/templates/introduction/#iteration.

However, we could open a separate issue and leave that for later, since it works right now. I'll comment on the PR, let's continue there.
