### ISSUE TITLE
How could I add Chinese translation

### ISSUE THREAD

**Issue by blueskyson** [numpy/numpy.org#462]
I want to add some Chinese translations (`zh` and `zh_TW`). Shall I just create pages under `content/zh` like #456, or is there any guide-line that I can follow?

**Comment by Qiyu8** [comment]
@blueskyson  Looking forward to collaborate with you! There's info at https://github.com/numpy/numpy/wiki/Translations-of-the-NumPy-website on Crowdin. Register an account and start translating. IMO #456 is just an summarization of Crowdin. Feel free to ask any questions if anything isn't clear enough.
