### ISSUE TITLE
Not centered

### ISSUE THREAD

**Issue by FayasNoushad** [numpy/numpy.org#469]
![Screenshot](https://user-images.githubusercontent.com/76828314/134862765-accd6af7-4b48-4079-8070-0cc27ef14e90.png)

Home page not centered on mobile view.

**Comment by melissawm** [comment]
@MarsBarLee do you think this is something you can look into?

**Comment by MarsBarLee** [comment]
@melissawm Yes I can! It seems to be an alignment problem.

**Comment by blackhat06** [comment]
I can take on this issue

**Comment by melissawm** [comment]
I am pretty sure this is fixed: ![Screenshot_2022-10-26-09-01-16-423-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/3949932/198021114-b5c01d3b-673b-4e5b-8f7e-012ee7fd5c55.jpg)

Are you still seeing this issue @blackhat06 ?

**Comment by blackhat06** [comment]
I am don't this issue
