### ISSUE TITLE
Science Tab under Ecosystem Section (Logos & Their Appearance on Mobile Devices)

### ISSUE THREAD

**Issue by new-vivek11** [numpy/numpy.org#474]
One cannot navigate all the logos under Science tab in Ecosystem section on main page very smoothly.

**If you slide the text written above the logos the site does not slide, not even if you slide on the logos.**

I have a moto g 6 and I opened Numpy.org on chrome browser.

**Comment by melissawm** [comment]
Thanks, @new-vivek11

**Comment by new-vivek11** [comment]
@melissawm also the logos under the Science tab look out of sync with the NumPy Color Palette.

Logos are black (although that is in the NumPy Color Palette), i feel they will look more in sync if they are drawn in another color which is also on the palette (RGB 1/50/67 | HEX #013243).

I think @MarsBarLee have designed them - she can do it in this color too - maybe later or sooner - or if i get to know how that is done, i can do that too.

**Comment by new-vivek11** [comment]
got a youtube video to change the color too : https://www.youtube.com/watch?v=jdEoTPZGTyQ&ab_channel=Basil
