### ISSUE TITLE
Add link on the home page for the survey content

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy.org#477]
Right now, the survey content lives here: [https://numpy.org/user-survey-2020/](https://numpy.org/user-survey-2020/)

However, this page is not reachable from the main page, only from the News section (which tends to get buried as time passes and new items are added).

It would be nice to find a place to link to the user survey page - maybe at the bottom links where we have the Roadmap, Press kit and other links. 

cc @InessaPawson and the survey team

**Comment by rgommers** [comment]
Good idea, more visibility would be nice. Now that the 2021 survey results are also on their way, the footer should perhaps be to a new https://numpy.org/user-surveys page?

**Comment by InessaPawson** [comment]
Sounds good to me! I’ll submit a PR shortly.
