### ISSUE TITLE
Change icon colors in Science tab of Ecosystem section

### ISSUE THREAD

**Issue by MarsBarLee** [numpy/numpy.org#478]
Change the colors of the icons in the Science tab of the Ecosystem section from black to the dark blue used in the rest of the theme, hex color code #013243.

Related to #474. This issue is to help separate the multiple issues mentioned in #474 into their own separate issues. @new-vivek11, would you like to continue with making the color changes?

**Comment by MarsBarLee** [comment]
@new-vivek11 You make a contribution by [making a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) in this [numpy.org repository](https://github.com/numpy/numpy.org/pulls).

If you're not already familiar with using Git on the command line, you can also make a pull request (PR) using the Github.com. 

You can make a fork of numpy.org repository. Then go to your fork and make a new branch. On that branch, you can replace the files with the new ones by deleting the old ones and uploading the new ones (there should be buttons for both 'delete' and 'add files'). Then you make a pull request from your branch to this [repository](https://github.com/numpy/numpy.org/pulls). This will open a new pull request page.

By making your own PR, you get contribution recognition to your account! :)

**Comment by new-vivek11** [comment]
i have made a pull request : https://github.com/numpy/numpy.org/pull/479

not sure whether i did it the right way or not but my guess is that i have done it right (new to pull requests) ... please let me know whether i have done all that i need to do from my side. @MarsBarLee
