### ISSUE TITLE
Logo size of icons in array libraries tab

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#489]
This is probably similar to #441 (unless I missed an issue to rework array libraries page).  Please resize to a standard size - all the logos in the first column on array libraries page. 
<img width="1008" alt="Screenshot 2021-10-26 at 3 05 54 PM" src="https://user-images.githubusercontent.com/5890484/138852077-92a56d16-2307-4e55-88fb-50b78dde876f.png">

**Comment by rgommers** [comment]
Agreed it doesn't look good, thanks for the report @shaloo. This is in general a hard thing to do right, because the aspect ratios of these logos are wildly different. We could do some resizing; PyData Sparse is in need of a better logo with a width larger than the height.

**Comment by MattiaAldighieri** [comment]
I'll try to work on this.
