### ISSUE TITLE
Link colors

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy.org#497]
I notice that links are currently colored [#1e87f0](https://imagecolorpicker.com/color-code/1e87f0) instead of using a color from the [NumPy palette](https://github.com/numpy/numpy.org#user-experience-ux).  This color derives from the usage of UIKit.

Should the color be one from the NumPy palette, should it be added to the palette, or should we leave things as-is?

For the theme, I've split the colors into two categories (primary and secondary, with light, standard, and dark variants a-la material UI).  But this introduces a fourth primary color that doesn't quite fit in.

/cc @isabela-pf

**Comment by InessaPawson** [comment]
Good catch! I’d stick with the NumPy palette. Let’s replace #1e87f0 with NumPy Deep Blue (#4d77cf ).

**Comment by isabela-pf** [comment]
That sounds good to me, too! Thanks @InessaPawson.

**Comment by olinjohnson** [comment]
Is this issue still open? I was wondering if I could work on it. This would be my first contribution.

**Comment by InessaPawson** [comment]
@olinjohnson Yes, the issue is still open. It would be great if you could take care of it.

**Comment by olinjohnson** [comment]
Alright, patched it up and submitted a pull request. #597
