### ISSUE TITLE
Contribute page does not have link to donation

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy.org#498]
And this may be where people land looking for it.

**Comment by InessaPawson** [comment]
Fair point! We should definitely add a paragraph about it and links/buttons.

**Comment by blackhat06** [comment]
I can own this issue and contribute to it

**Comment by melissawm** [comment]
Hi @blackhat06 - feel free to try! I think there are still a couple of things we should decide, though.

1. We should add a link to https://numpy.org/about/#donate in the https://numpy.org/contribute page
2. The link to donate through NumFOCUS in https://numpy.org/about/#donate points to [this page](https://numfocus.org/donate-to-numpy), which looks outdated and should probably be replaced by https://opencollective.com/numpy
3. The links in https://numpy.org/about/#donate should probably reflect the same content as the `Sponsor this project` section on https://github.com/numpy/numpy

Does this seem reasonable?

**Comment by blackhat06** [comment]
These seems reasonable to me.

**Comment by BhaswatiRoy** [comment]
Hello @melissawm 
I can work on this issue
