### ISSUE TITLE
Add image preview to case studies section

### ISSUE THREAD

**Issue by logankilpatrick** [numpy/numpy.org#499]
It would be nice visually to have some preview images on this page: https://numpy.org/case-studies/ instead of just all text.

**Comment by rgommers** [comment]
Hmm, that was never meant to be a page I think. Did you find a link to it somewhere?

**Comment by logankilpatrick** [comment]
I saw a direct link @stefanv sent and just deleted the rest of the URL because I wanted to see the other case studies

**Comment by stefanv** [comment]
That's a category page on Hugo. It's like a list of posts, so you wouldn't expect to find anything other than text (usually title, author, and summary). The site never links to it explicitly, so I think it's safe to leave as-is.
