### ISSUE TITLE
Missing link in gallery/team.html

### ISSUE THREAD

**Issue by ganesh-k13** [numpy/numpy.org#503]
### Issue:
There is a missing hyperlink at `Governance` section of https://numpy.org/gallery/team.html to https://numpy.org/devdocs/dev/governance/people.html

Related to https://github.com/numpy/numpy/issues/17496

CC: @InessaPawson

**Comment by InessaPawson** [comment]
@ganesh-k13 Thank you for identifying the broken link! Since https://numpy.org/devdocs/dev/governance/people.html has been deleted, let's link to the list of the Steering Council members on https://numpy.org/about/.

**Comment by jarrodmillman** [comment]
I believe #509 closes this.  Re-open if I am mistaken.
