### ISSUE TITLE
Cleanup existing team gallery

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#513]
Here is an improvised version of team gallery. I created this over the holidays when @InessaPawson asked about team page and script usage.

New:
<img width="1066" alt="Screenshot 2022-01-05 at 7 43 38 PM" src="https://user-images.githubusercontent.com/5890484/148246457-5d000969-8c98-4f18-8020-7a9156a50253.png">

 Older version:  <img width="1074" alt="Screenshot 2022-01-05 at 7 43 44 PM" src="https://user-images.githubusercontent.com/5890484/148246368-82717457-a8df-4877-add5-c7d0ae403377.png">

@rgommers just pointed me to https://github.com/numpy/numpy.org/pull/510 which is a great idea. So it is okay if this PR does not get merged or gets superseded by https://github.com/numpy/numpy.org/pull/510.

**Comment by jarrodmillman** [comment]
Closing b/c #510 merged (reopen if this was an error on my part).
