### ISSUE TITLE
Teams Gallery: make teams requires requests package to be pre-installed

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#517]
Ref #510 

I used a fresh new pyenv virtualenv to run teams target.  When I run `make teams` target to build teams gallery,  it requires python requests package.  There is no requirements.txt in NumPy.org repo anymore.  Do we need to state this in README or am I missing something?

After installing requests package in my virtualenv, it worked fine.

>>>>Log for reference

BEFORE:
numpy.org % pip3 list
Package    Version
---------- -------
pip        21.2.3
setuptools 57.4.0

numpy.org % make teams
Submodule 'themes/scientific-python-hugo-theme' (https://github.com/scientific-python/scientific-python-hugo-theme.git) registered for path 'themes/scientific-python-hugo-theme'
Cloning into '/<PATH>/ssnumpyfork/numpy.org/themes/scientific-python-hugo-theme'...
Submodule path 'themes/scientific-python-hugo-theme': checked out '1ee3eb51cb7a9496bac2432b99ed73cb734c5609'
Submodule 'themes/hugo-fresh' (https://github.com/StefMa/hugo-fresh.git) registered for path 'themes/scientific-python-hugo-theme/themes/hugo-fresh'
Cloning into '<PATH>/ssnumpyfork/numpy.org/themes/scientific-python-hugo-theme/themes/hugo-fresh'...
Submodule path 'themes/scientific-python-hugo-theme/themes/hugo-fresh': checked out '17f51372b615e3c92d44d79f1edfd2fd1866aec7'
Traceback (most recent call last):
  File "<PATH>/ssnumpyfork/numpy.org/themes/scientific-python-hugo-theme/tools/team_query.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
make: *** [static/gallery/emeritus-maintainers.md] Error 1

AFTER installing requests package (and other dependencies automatically), it worked:

numpy.org % pip3 list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.10
idna               3.3
pip                21.2.3
requests           2.27.1
setuptools         57.4.0
urllib3            1.26.7

numpy.org % make teams
Teams dir: emeritus-maintainers
Teams dir: maintainers
Teams dir: triage-team
Teams dir: survey-team
Teams dir: web-team

**Comment by stefanv** [comment]
It's true, the script requires `requests`.  It is only run every so often, not when building the website, so I'm not sure it's worth adding a requirements.txt just for that.  Maybe a comment in the README, or we can update the script to fail with a helpful message when `requests` is not found?

**Comment by shaloo** [comment]
> It's true, the script requires `requests`. It is only run every so often, not when building the website, so I'm not sure it's worth adding a requirements.txt just for that. Maybe a comment in the README, or we can update the script to fail with a helpful message when `requests` is not found?

ok, added via #518 fixes
