### ISSUE TITLE
Add a link to the official NumPy YouTube channel 

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#533]
At the latest NumPy community call, it was suggested to add a link to the NumPy YouTube channel (https://www.youtube.com/channel/UCguIL9NZ7ybWK5WQ53qbHng) to numpy.org.
I’d like to hear everyone’s thoughts on where this link should be placed.

**Comment by melissawm** [comment]
My suggestion is the Learn page - https://numpy.org/learn :)

**Comment by shaloo** [comment]
...to be specific the first one - newcomers hour video can go under  https://numpy.org/learn/ under section 'Beginners > Videos'. 

Ralf's talk (the second video on the link - Scipy 2019 on state of NumPy, funding etc) could go under 'Advanced > NumPy Talks section.

**Comment by rgommers** [comment]
Those suggestions sound good to me.

**Comment by jarrodmillman** [comment]
I would also it to the social media links at the bottom of the page.

Here is what they look like currently on numpy.org:
![screenshot](https://user-images.githubusercontent.com/123428/150610212-b8e4675c-a0e4-499d-98cf-67a2c135aa3a.png)

Here is what they look like for scientific-python.org:
![screenshot](https://user-images.githubusercontent.com/123428/150610254-32d86611-6f7a-45b9-bfc1-830173d13045.png)

**Comment by jarrodmillman** [comment]
The theme also a youtube shortcode:
https://theme.scientific-python.org/shortcodes/

This let's you embedded individual videos (including transcripts).

**Comment by jarrodmillman** [comment]
See #536.

**Comment by InessaPawson** [comment]
Thank you for your input, everyone! I’d like to offer my thoughts on this.:) The recommended videos in the Beginners and Advanced sections of learn.md are intended for NumPy users, while the target audience of Ganesh’s presentation is contributors to the NumPy codebase. I'm not sure that the Beginners section is the best place for this video.

We could possibly start a new section on learn.md titled “Contributing to NumPy” and list Ganesh’s video there along with Melissa’s and Matti’s ones (for Data Umbrella). Another option could be adding the list of the videos on contributing to NumPy to https://numpy.org/contribute/ under Writing Code.

**Comment by InessaPawson** [comment]
Please view #542 as one of the possible solutions in this discussion.
