### ISSUE TITLE
Automate link checking

### ISSUE THREAD

**Issue by axil** [numpy/numpy.org#538]
The page 'Learn NumPy' (https://numpy.org/learn/) contains a broken link.

> "For the latest copy (2015) see here."

—the 'here' link is broken.

Can we automate link checking?

**Comment by axil** [comment]
From slack:

> Rohit Goswami: 
> – https://github.com/stevenvachon/broken-link-checker seems to be pretty good
> – @melissawm mentioned lychee which works well for markdown, and there's a sphinx checker too for ReST but me and @Ross Barnowski prefer something on the output HTML
> Ross Barnowski: 
> — Stefan mentioned linkchecker: https://github.com/scientific-python/scientific-python-hugo-theme/issues/97

**Comment by axil** [comment]
I've found a single python file which does it for sphinx
https://www.sphinx-doc.org/en/master/_modules/sphinx/builders/linkcheck.html
It should probably work fast enough.

**Comment by axil** [comment]
This one also claims to run fast:
https://github.com/filiph/linkcheck

**Comment by mattip** [comment]
Did you try any of them?

**Comment by axil** [comment]
Yes, trying now :)

**Comment by axil** [comment]
This one looks most promising to me https://github.com/scivision/linkchecker-markdown :

```
> linkcheckMarkdown .
('code-of-conduct.md', '/report-handling-manual#resolutions')

 ('community.md', 'https://tidelift.com/docs/security', 403)

 ('diversity_sep2020.md', 'https://scipy.org/scipylib/mailing-lists.html#mailing-lists', 404)

 ('learn.md', 'https://www.barnesandnoble.com/w/guide-to-numpy-travis-e-oliphant-phd/1122853007', 403)
33.1 seconds to check links
```

Checking html is good, but it cannot be efficiently built into the continuous integration. 

I've also stopped https://github.com/filiph/linkcheck after 10-15 minutes of running it (it crawled 4051 pages). It only makes sense to run it against localhost serving the whole site. I don't have the whole numpy.org deployed locally to check it.

**Comment by stefanv** [comment]
See also: https://github.com/scientific-python/scientific-python.org/pull/177
