### ISSUE TITLE
Icon error in "back to top" element in lower-right corner

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy.org#544]
On the main `numpy.org` page, if a user scrolls down so that the top of the page is no longer visible, a small gray circle appears in the lower-right hand corner of the page which is an anchor link to take the user back to the top of the page. It looks like there is some sort of unicode character that is supposed to render in this bubble, but on my system this doesn't show up. For lack of a better description, I've attached a screenshot with the icon highlighted in pink:

![numpy_org_icon](https://user-images.githubusercontent.com/1268991/151861245-0d474278-0638-47f8-aad3-fa726aa33d0c.png)

This very well could be a browser/OS font issue, but I figured I'd raise it here anyways.

**Comment by WarrenWeckesser** [comment]
On my system (Linux + Firefox), the circle contains an up arrow (well, more like a big circumflex--the arrowhead without the shaft):

![Screenshot from 2022-01-31 16-03-37](https://user-images.githubusercontent.com/321463/151872799-e69a761c-3c16-4817-a335-32c17b255d3f.png)
.

**Comment by mattip** [comment]
On macOS safari I see a box like a bad unicode font.

**Comment by rossbar** [comment]
Thanks @WarrenWeckesser , it looks like this is the [u+2303](https://www.fileformat.info/info/unicode/char/2303/index.htm) unicode character. It's strange because my system font supports this character, but maybe I have a weird configuration somewhere.

Replacing the unicode character with an icon etc. or some other solution to decouple this from the font support of each user's system would make the site more robust.

**Comment by WarrenWeckesser** [comment]
I think it is actually coming from here:

https://github.com/scientific-python/scientific-python-hugo-theme/blob/eaae4491172d327f01270a737679cf9693333826/assets/css/fresh/partials/_utils.scss#L89

So the character is U+F106

**Comment by WarrenWeckesser** [comment]
Hmmm... U+F106 is in a [private use area](https://en.wikipedia.org/wiki/Private_Use_Areas).  This looks like a "Font Awesome" issue, perhaps something similar to https://github.com/FortAwesome/Font-Awesome/issues/11946

**Comment by stefanv** [comment]
We removed font awesome, so need to put back an icon for that feature.
