### ISSUE TITLE
Docs team is missing on the Teams page

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#559]
Documentation Team is missing on https://numpy.org/teams/.

**Comment by stefanv** [comment]
I don't see a documentation team. Can you add one at https://github.com/orgs/numpy/teams ?

**Comment by InessaPawson** [comment]
Will do. We used to have it. Not sure what happened there.

**Comment by InessaPawson** [comment]
@melissawm and I re-established the NumPy Docs team on GitHub. 
@stefanv, you may go ahead with adding the team to https://numpy.org/teams/.

**Comment by stefanv** [comment]
@InessaPawson I still see no team at https://github.com/orgs/numpy/teams

**Comment by stefanv** [comment]
See https://github.com/numpy/numpy.org/pull/560
