### ISSUE TITLE
Twitter cards don't support SVG

### ISSUE THREAD

**Issue by jarrodmillman** [numpy/numpy.org#591]
The twitter card currently has `<meta name=twitter:image content="https://numpy.org/images/logo.svg">`, but twitter cards don't render SVG images:
```
twitter:image

A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used.

SVG is not supported.
```

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

**Comment by jarrodmillman** [comment]
See #590.

**Comment by ErnestoFGonzalez** [comment]
Hi @jarrodmillman. I'm trying to take a look at this and see reference to a `_internal/twitter_cards.html` in `baseof.html` but can't find it on my search. 

How can I generate the `_internal` folder?

**Comment by stefanv** [comment]
The twitter card is built into Hugo: https://gohugo.io/templates/internal/#twitter-cards

See https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html

**Comment by ErnestoFGonzalez** [comment]
> The twitter card is built into Hugo: https://gohugo.io/templates/internal/#twitter-cards
> 
> See https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html

Ah, ok. Thanks! New to Hugo. Let me take a look at it and then I'll submit a PR.
