### ISSUE TITLE
No visible link to the list of releases with dates.

### ISSUE THREAD

**Issue by charris** [numpy/numpy.org#614]
The top news item is displayed on the landing page, but I see no way to see the list of releases. It also seems that the 1.23.x micro releases don't show up in the release notes section. This may be an error in the release walkthrough, as documentation is not generated for micro-releases. Perhaps they will show up with the 1.24.0 release.

**Comment by mattip** [comment]
There is a [news](https://numpy.org/news/) page you get to via the banner on the landing page. It might be nice to add a "see more news" link to the banner to make it explicit that there are more items.

> It also seems that the 1.23.x micro releases don't show up in the release notes section

Which release notes section? Do you mean in the rendered docs from numpy/numpy? They don't appear in the [stable](https://numpy.org/doc/stable/release.html) version, but do in the [devdocs](https://numpy.org/devdocs/release/1.21.5-notes.html). At one time we discussed re-deploying the docs for micro releases, but I think we decided not to re-deploy. Maybe we should revisit that decision.

**Comment by InessaPawson** [comment]
@charris @mattip Release notes for all the NumPy micro releases are now visible (with active links) in the stable version of the NumPy documentation as well. 
Please refer to the screenshot below:
<img width="1417" alt="stable-microreleases-info" src="https://user-images.githubusercontent.com/43481325/217843200-0b44e9f0-201c-43e1-9482-607977a7879d.png">

**Comment by InessaPawson** [comment]
> The top news item is displayed on the landing page, but I see no way to see the list of releases. 

What do you think of adding the number of a latest NumPy release right next to the logo on the home page which would link to https://numpy.org/news/#releases?
Here is how it could look:
<img width="1435" alt="numpyorg-release-info" src="https://user-images.githubusercontent.com/43481325/217851615-b8fb8547-2407-46e6-b74f-0706b97b6cb5.png">

**Comment by charris** [comment]
We could combine some of the elements of the [PyPI landing page](https://pypi.org/project/numpy/). Maybe a latest version box with a release date.
