### ISSUE TITLE
Adding package to ecosystem

### ISSUE THREAD

**Issue by tinosulzer** [numpy/numpy.org#620]
What is the process for submitting a package to be added to the ecosystem on the home page?

**Comment by melissawm** [comment]
Hi @tinosulzer - not sure there is a process 😄  But we can have this discussion here or, as an example, you can check https://github.com/numpy/numpy.org/pull/611

**Comment by tinosulzer** [comment]
Hi @melissawm , thanks! I'd like to propose [PyBaMM](https://github.com/pybamm-team/PyBaMM), a Python package for battery modeling that recently became a NumFOCUS sponsored project. I think it would fit under the "chemistry" category

**Comment by stefanv** [comment]
Fine with me!

**Comment by MattiaAldighieri** [comment]
I can work on adding it.

**Comment by InessaPawson** [comment]
@tinosulzer Congratulations on becoming a NumFOCUS sponsored project! 
+1 from me for adding PyBaMM to the [numpy.org](http://numpy.org/) homepage.

**Comment by tinosulzer** [comment]
Woohoo! Thanks!
