### ISSUE TITLE
Release block on landing page shows overflowing text

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy.org#636]
On Linux, both Firefox and Chrome seem to have trouble displaying the full text inside the block meant to show the latest release. See screenshots for details:

Firefox:
![Screenshot_20230405_094926](https://user-images.githubusercontent.com/3949932/230087538-07fee537-d25d-4532-9a16-2e7f2af35c5a.png)

Chrome:
![Screenshot_20230405_095750](https://user-images.githubusercontent.com/3949932/230087576-277cb575-17d0-4bf5-990b-cc9bd91bd4f6.png)

On macOS, this looks better:
<img width="1068" alt="Screenshot 2023-04-05 at 9 59 24 AM" src="https://user-images.githubusercontent.com/3949932/230087907-022bb244-d417-4ecc-b929-84fa97516b8a.png">

**Comment by InessaPawson** [comment]
@melissawm Thank you for submitting this issue. Could you please check if it persists with the new Scientific Python Hugo Theme?

**Comment by melissawm** [comment]
It doesn't, now I get a really nice element 😄 
![Screenshot_20240304_131725](https://github.com/numpy/numpy.org/assets/3949932/838ed420-9cd4-4972-9009-ee60ad21fa29)

Closing as resolved, thanks for the ping!
