### ISSUE TITLE
Server Not Starting 

### ISSUE THREAD

**Issue by VedantBhawsar** [numpy/numpy.org#650]
I am trying to run the website on my localhost but the file is not running. also give and error called 

> Error: command error: failed to create config from result: failed to decode config for language "en": unknown config key "arraylibraries"

just i run the hugo server in my windows laptop. please help me to solve this issue 

- hugo extended version installed.
- lastest python installed.

**Comment by stefanv** [comment]
Which version of Hugo are you using? We're still sorting out some issues with the latest Hugo: https://github.com/numpy/numpy.org/pull/649

**Comment by VedantBhawsar** [comment]
> Which version of Hugo are you using? We're still sorting out some issues with the latest Hugo: #649

This version : - v0.114.1-e9b716ad9869b79e7c374bbdae4daf5ee6406bd4+extended

**Comment by stefanv** [comment]
Yes, please use hugo <0.112 until we can resolve #649.

**Comment by VedantBhawsar** [comment]
`Error: command error: failed to create config from result: failed to decode config for language "en": unknown config key "arraylibraries"`

Sir, I am still getting the same error I checked the config file their is has empty value for `arraylibraries` is this issue sir ?
and also I am using  windows 10 operating system  
Like this 
`arraylibraries:`

**Comment by VedantBhawsar** [comment]
> Yes, please use hugo <0.112 until we can resolve #649.

Thank You Sir
