### ISSUE TITLE
Website looks weird, stable doc gives 404

### ISSUE THREAD

**Issue by pllim** [numpy/numpy.org#664]
I am using Chrome on Windows 10.

https://numpy.org/ looks weird, like this:

![Screenshot 2023-08-01 151716](https://github.com/numpy/numpy.org/assets/2090236/446008a6-54b0-4874-ac06-75e51bf200cc)

And https://numpy.org/doc/stable/ giving me HTTP Error 404

**Comment by stefanv** [comment]
Sorry about that, I'm busy reconfiguring deployment. Should have that back in a few minutes.
