### ISSUE TITLE
Update Footer Layout

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#67]
Update the footer layout. See the below image (keep 'old' NumPy logo): 
<img width="1679" alt="Screen Shot 2019-11-10 at 8 51 52 PM" src="https://user-images.githubusercontent.com/3891660/68557605-fc224380-03fb-11ea-974f-de6c7b8ba27a.png">

Question: how should an email list function? Should these be written to S3? Emailed to someone?

**Comment by rgommers** [comment]
Nice! 

> Question: how should an email list function? Should these be written to S3? Emailed to someone?

I'm not sure. I think this came from @InessaPawson's design of the footer, and she had in mind not our regular mailing list but a newsletter? Our regular mailing list signup is documented at https://scipy.org/scipylib/mailing-lists.html. For a newsletter, I have no practical experience with how to do that. I think it requires hooking up to some interface that lets people unsubscribe as well. NumFOCUS has that, I can ask them unless anyone has a good idea for this.

**Comment by joelachance** [comment]
A couple ideas:
1. There are a couple of services we could use, but I believe  most of them would cost some $$. 
2. We could also call a Lambda that would save it somewhere (S3, maybe), but I'm not sure if we have access to any type of cloud functions. 
3. We could simply re-direct users to the current site and keep that going.

I'm not sure what resources we have for something like this. I would be curious what NumFOCUS has to say.

**Comment by InessaPawson** [comment]
Indeed, this is a subscription form for our future newsletter. I’ve been using  Mailchimp for over a decade. I'm always pleased with the service. This is how you add the Mailchimp sign up form to a website: mailchimp.com/help/add-a-signup-form-to-your-website/
I can see that NumFOCUS uses Salsa Labs. It would be helpful to hear what they think of it.

**Comment by InessaPawson** [comment]
This is a link to the proposed footer layout: https://app.moqups.com/GDnB7Jy2HN/view
Feedback is welcome.

**Comment by rgommers** [comment]
> This is a link to the proposed footer layout: https://app.moqups.com/GDnB7Jy2HN/view
Feedback is welcome.

I think you need to click a button to give me access, it's protected it seems.

> Indeed, this is a subscription form for our future newsletter. I’ve been using Mailchimp for over a decade. I'm always pleased with the service. This is how you add the Mailchimp sign up form to a website: https://mailchimp.com/help/add-a-signup-form-to-your-website/
I can see that NumFOCUS uses Salsa Labs. It would be helpful to hear what they think of it.

Sounds good. I read some reviews, and Mailchimp seems like a good choice. I know there were some issues with Salsa Labs, at least with their donation forms. 

I think it's an important factor that you're already so familiar with Mailchimp, that will reduce the effort to get started. I'd be happy to go with your recommendation here.

**Comment by InessaPawson** [comment]
@rgommers My apologies! Let's try again!

**Comment by InessaPawson** [comment]
> > Indeed, this is a subscription form for our future newsletter. I’ve been using Mailchimp for over a decade. I'm always pleased with the service. This is how you add the Mailchimp sign up form to a website: https://mailchimp.com/help/add-a-signup-form-to-your-website/
> > I can see that NumFOCUS uses Salsa Labs. It would be helpful to hear what they think of it.
> 
> Sounds good. I read some reviews, and Mailchimp seems like a good choice. I know there were some issues with Salsa Labs, at least with their donation forms.
> 
> I think it's an important factor that you're already so familiar with Mailchimp, that will reduce the effort to get started. I'd be happy to go with your recommendation here.

Mailchimp is great! Also it's free if our contact list is kept under 2k.

**Comment by rgommers** [comment]
The footer layout looks visually appealing, I like it. Regarding the choice of links, there's 3 columns:

- column 1 is partly overlapping with the main page links at the top of the page
- column 2 is how to interact with us
- column 3 is legal & marketing

is that the design principle?

For column 2, I would consider adding Community. For column 1 I would replace Release Notes with Learning (release notes aren't that important).

Overall we can add/change some links later, the big picture looks right to me.

**Comment by rgommers** [comment]
> Also it's free if our contact list is kept under 2k.

ah, that may not last - if 0.1% of visitors sign up, we'll be at the limit within a year.

**Comment by InessaPawson** [comment]
> The footer layout looks visually appealing, I like it. Regarding the choice of links, there's 3 columns:
> 
> * column 1 is partly overlapping with the main page links at the top of the page
> * column 2 is how to interact with us
> * column 3 is legal & marketing
> 
> is that the design principle?

The thinking behind the presented footer design is as follows. A footer is the last chance for a user to find the information she/he is searching for and offer additional information they might find useful.
Using Google AdWords Keyword Planner, I’ve identified the most popular search terms related to NumPy. Here are the findings:
install numpy
numpy tutorial
numpy array
numpy version
numpy python 3
(Some results were omitted due to the similarity to the terms above.)

I’ve designed the content of the footer keeping in mind this info, and trying to anticipate the key needs of all NumPy stakeholders. And, there is the required legal info, of course. 

@rgommers You are right about the thinking behind grouping into 3 columns. Sometimes footer columns end up being a medley though. I think it’s far more important to link to the pages that contain the information users search the most. In about 6 months after the launch of the new version we shall look at the website statistics, specifically the most visited pages, and reevaluate the footer content.

> For column 2, I would consider adding Community. For column 1 I would replace Release Notes with Learning (release notes aren't that important).

Done.

**Comment by InessaPawson** [comment]
I’ve added a YouTube icon to the social media links.

**Comment by InessaPawson** [comment]
A slightly enhanced version of the same footer.
<img width="750" alt="numpy_footer_v2 0" src="https://user-images.githubusercontent.com/43481325/69017301-11571f00-0974-11ea-8235-28bfcba6ba76.png">
https://app.moqups.com/GDnB7Jy2HN/edit/page/afd330016

**Comment by rgommers** [comment]
That looks great, and I like the _Google AdWords Keyword Planner_ approach.

**Comment by InessaPawson** [comment]
A footer acknowledging all the organizations, in alphabetical order, supporting NumPy.

<img width="780" alt="footer_sponsors" src="https://user-images.githubusercontent.com/43481325/69018407-53835f00-097a-11ea-95b6-015025409dd5.png">
https://app.moqups.com/GDnB7Jy2HN/edit/page/adc153396

**Comment by joelachance** [comment]
@InessaPawson 

- [ ] Integrate MailChimp
