### ISSUE TITLE
Citing NumPy

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#68]
Publish an example for citing NumPy in academic publications.

**Comment by rgommers** [comment]
Good point, we need that on the website. Content can be copied from https://scipy.org/citing.html#numpy

**Comment by InessaPawson** [comment]
https://docs.google.com/document/d/1fAZOAw-IljHUDSJYFOLa6Xe4IJwamT9GjArTWxj5stk/edit?usp=sharing
