### ISSUE TITLE
@gokceneraslan a division by a positive number is well-conditioned therefore I think it is quite safe to to divide by `log(2)`.

### ISSUE THREAD

**Issue by akingatwork** [numpy/numpy.org#689]
@gokceneraslan a division by a positive number is well-conditioned therefore I think it is quite safe to to divide by `log(2)`.

_Originally posted by @lewlin in https://github.com/numpy/numpy/issues/14969#issuecomment-

557833663_https://github.com/numpy/numpy/issues/14969#issuecomment-558826039
In [215]: import mpmath

In [216]: mpmath.mp.dps = 50

In [217]: x = 1.5e-24

In [218]: y = mpmath.log(mpmath.mp.one + x, b=2)

In [219]: y
Out[219]: mpf('2.1640425613334450784151339045869271953211073610684447e-24')

In [220]: float(y)
Out[220]: 2.1640425613334452e-24In [221]: def log2_1p(x): 
     ...:     return np.log1p(x) / 0.6931471805599453  
     ...:                                                                       

In [222]: log2_1p(x)
Out[222]: 2.1640425613334452e-24

**Comment by rkern** [comment]
It looks like you intended to reply to an issue in another repository instead of opening a new issue here.
