### ISSUE TITLE
Get Help IRC still points to freenode

### ISSUE THREAD

**Issue by deliciouslytyped** [numpy/numpy.org#700]
https://numpy.org/gethelp/ still refers to the numpy IRC channel on freenode, which had some hostile takeover problems and now many if not most communities (and the previous operators of freendoe) have moved to libera.chat .

**Comment by stefanv** [comment]
Thanks @deliciouslytyped; do you have a new URL to put in its place? If you make a PR, or give me the URL, I'd be happy to get that change in.

**Comment by mattip** [comment]
I think we should remove IRC and gitter from that page.

**Comment by deliciouslytyped** [comment]
There appears to be a few users in the #numpy channel, a link like this works: https://web.libera.chat/gamja/#numpy .
There is further information under https://libera.chat/guides/webchat , https://libera.chat/guides/ , and https://libera.chat/guides/faq .

**Comment by InessaPawson** [comment]
I would be in favor removing links to the communication channels we are not actively monitoring from numpy.org.

**Comment by InessaPawson** [comment]
@deliciouslytyped We discussed this issue at today’s community meeting and agreed to remove IRC and gitter from the [Get Help page](https://numpy.org/gethelp).

**Comment by InessaPawson** [comment]
@deliciouslytyped We discussed this issue at today’s community meeting and agreed to remove IRC and Gitter from the [Get Help page](https://numpy.org/gethelp).
