### ISSUE TITLE
## Deploying with &nbsp;<a href="https://pages.dev"><img alt="Cloudflare Pages" src="https://user-images.githubusercontent.com/23264/106598434-9e719e00-654f-11eb-9e59-6167043cfa01.png" width="16"></a> &nbsp;Cloudflare Pages

### ISSUE THREAD

**Issue by akingatwork** [numpy/numpy.org#721]
## Deploying with &nbsp;<a href="https://pages.dev"><img alt="Cloudflare Pages" src="https://user-images.githubusercontent.com/23264/106598434-9e719e00-654f-11eb-9e59-6167043cfa01.png" width="16"></a> &nbsp;Cloudflare Pages

<table><tr><td><strong>Latest commit:</strong> </td><td>
<code>36defa5</code>
</td></tr>
<tr><td><strong>Status:</strong></td><td>&nbsp;✅&nbsp; Deploy successful!</td></tr>
<tr><td><strong>Preview URL:</strong></td><td>
<a href='https://ec66c08c.cloudflare-docs-7ou.pages.dev'>https://ec66c08c.cloudflare-docs-7ou.pages.dev</a>
</td></tr>
<tr><td><strong>Branch Preview URL:</strong></td><td>
<a href='https://rebecca-dns-firewall-respons.cloudflare-docs-7ou.pages.dev'>https://rebecca-dns-firewall-respons.cloudflare-docs-7ou.pages.dev</a>
</td></tr>
</table>

[View logs](https://dash.cloudflare.com/?to=/:account/pages/view/cloudflare-docs/ec66c08c-3cd4-4ab3-ad41-1c87d5a22fc6)

_Originally posted by @cloudflare-pages in https://github.com/cloudflare/cloudflare-docs/pull/12561#issuecomment-1896325106_

**Comment by melissawm** [comment]
Sorry - I'm not sure what this means. Please re-open if appropriate.
