### ISSUE TITLE
pyjanitor link seems to be incorrect

### ISSUE THREAD

**Issue by prajwel** [numpy/numpy.org#748]
I was going through the NumPy website. It appears to me that the pyjanitor link is incorrectly pointing to something else. The correct link should be https://pyjanitor-devs.github.io/pyjanitor/. Please see: 
https://github.com/search?q=repo%3Anumpy%2Fnumpy.org+pyjanitor&type=code

**Comment by InessaPawson** [comment]
@prajwel The link is outdated indeed. Thank you for catching it! Would you like to file a PR to fix it?
