### ISSUE TITLE
Add a "Translation Team" to the teams page

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy.org#796]
I was thinking about the best way to credit translators for the NumPy.org page, and I thought this might be a good idea. I'd like to propose using the Teams gallery page provided by the scientific python hugo theme to show a "Translation Team".

The only issue is that right now the Teams page is sourced directly from GitHub teams, and there are two problems there:
- There is no translation team on github (but this would be easily fixed)
- Not every translator has a github account - they log in to Crowdin with potentially other credentials.

If there is interest and consensus, could we have a manual section on the teams page to add translators? Or source them directly from crowdin?

cc @steppi

**Comment by rgommers** [comment]
👍🏼 from me - in general we like to acknowledge any type of significant contribution, and translations contributions deserve that as well (doubly so because they're less visible; no commit stats to look at in the GitHub UI).

**Comment by InessaPawson** [comment]
@melissawm Another thumbs up from me. Thank you for facilitating these contributions! 
As far as an approach for creating this team's section, what are the drawbacks of syncing with crowdin?

**Comment by melissawm** [comment]
I am not sure I would go with that option right now as it seems like a very large lift. Looking at https://github.com/numpy/numpy.org/blob/4d22f788d7dfa6f0624bede75d85a8c6e7f672bd/content/en/teams/index.md?plain=1#L4 I think if we add a manual toml file this should work? I think we can rely on a manual update for now and think about a potential automation in the future.
