### ISSUE TITLE
add "fiscally sponsored by NumFOCUS" logo to website

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#8]
Examples: http://mc-stan.org/, https://quantecon.org/, http://ropensci.org/

**Comment by cheralathann** [comment]
@rgommers I have added the numfocus logo. But I need permission to upload.

**Comment by rgommers** [comment]
Thanks @cheralathann. Can you please send your changes as a pull request? We'll review them first, and on merging the PR they will be uploaded to numpy.org

**Comment by cheralathann** [comment]
I don't know how to push the changes to sub modules. can you give me some instructions.

**Comment by rgommers** [comment]
Sorry @cheralathann, I was busy for a while and this issue has been fixed already in gh-10. Thanks for stepping up to work on it!
