### ISSUE TITLE
Create copy for the NumPy terminal

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#81]
We need to create copy above the NumPy terminal on the homepage. A welcoming message and perhaps a code sample might be nice. Ideas welcome.

**Comment by rgommers** [comment]
(moving comment from @shaloo to here):

Here are some more ideas for copy / layout and example code in terminal on the landing page - refer to attached image, blue text.

<img width="1247" alt="numpy-issue83-inputs" src="https://user-images.githubusercontent.com/5890484/69939774-a9254300-1506-11ea-9fb9-4a017f788d24.png">

**Comment by stefanv** [comment]
Probably worth getting PEP8 right on the landing page, so `np.linspace(0, 10)` instead of `np.linspace(0,10)`, etc.

**Comment by rgommers** [comment]
I've thought about it some more; it's quite hard to show much in a few lines of code. 

Perhaps something like this, showing array creation, indexing and using a method over one axis:
```
>>> x = np.arange(15, dtype=np.float64).reshape(3, 5)                              
>>> x[1:, ::2] = -99                                                               
>>> x                                                                              
array([[  0.,   1.,   2.,   3.,   4.],
       [-99.,   6., -99.,   8., -99.],
       [-99.,  11., -99.,  13., -99.]])
>>> x.max(axis=1)                                                                  
array([ 4.,  8., 13.])
```

**Comment by stefanv** [comment]
Maybe make the dtype `int64` to save on all the printing of dots?

**Comment by rgommers** [comment]
Okay:)
```
>>> x = np.arange(15, dtype=np.int64).reshape(3, 5)                                
>>> x[1:, ::2] = -99                                                               
>>> x                                                                              
array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])
>>> x.max(axis=1)                                                                  
array([ 4,  8, 13])
```
