### ISSUE TITLE
Icon in the 'Back to Top' link misaligned horizontally

### ISSUE THREAD

**Issue by headlessNode** [numpy/numpy.org#812]
The icon inside the "Back to Top" link on the website appears to be horizontally off-center. 

As the parent is a `flex` container, using `justify-content` should fix the misalignment.

Let me know if you'd like me to submit a PR for this change!

**Comment by stefanv** [comment]
Thanks for the report! Can you please check if https://theme.scientific-python.org has the same problem?

**Comment by headlessNode** [comment]
Yes, same issue present there. 

Also, on the `User Guide` and `Examples` page the breadcrumbs container overlaps the `More` dropdown in the navbar.
![image](https://github.com/user-attachments/assets/bb4431a6-94b4-4178-b977-4c421cea3b6f)

This is because the breadcrumbs containers' `z-index` is set to `99` whereas, the `z-index` of the dropdown is set to `20`

**Comment by headlessNode** [comment]
@stefanv Just to confirm, should I open the PR on this repository or the theme repository?

**Comment by stefanv** [comment]
On the theme repo, please. Unless the CSS is custom CSS that lives in this repo, but mainly it uses the theme "as-is".

**Comment by headlessNode** [comment]
Closing this issue as I've open related PR on the theme repo.
