### ISSUE TITLE
Homepage - Case Studies - Content

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#82]
Add "Case studies" tiles.
Place the segment below "In a nutshell".

**Comment by rgommers** [comment]
There's two tasks here:

1. Add one or more case studies, as separate pages
2. Add a tile widget on the front page that links to the case study/studies.

These tasks are basically independent. We have content for one case study at the moment - the EHT black hole image (@shaloo already did the concept and diagram). Also there's https://numfocus.org/case-studies/first-photograph-black-hole. We could link to that, and keep our show case shorter and more focused on the role of NumPy (e.g. the graphviz diagram of dependencies of the imaging pipeline).

I would put the page under `content/en/showcase/black_hole_image.md`.

**Comment by InessaPawson** [comment]
Agreed! I’ll open a separate issue for the design part of this task.

**Comment by shaloo** [comment]
Inessa, let me know if I can help with a crisp summary of NumPy's role in case study tile widget.  Once you are done with design (placeholder content), I can improvise. Okay?  May be this is what @rgommers suggested.  Here is a first shot that might be of help to you.
<img width="847" alt="Screenshot 2020-01-06 at 10 46 43 AM" src="https://user-images.githubusercontent.com/5890484/71796893-fcdcfc00-3071-11ea-8b98-765678cf53b7.png">

**Comment by shaloo** [comment]
I've only focussed on content - I'll leave it to you to wave your layout magic wand :-)

**Comment by InessaPawson** [comment]
> Inessa, let me know if I can help with a crisp summary of NumPy's role in case study tile widget. Once you are done with design (placeholder content), I can improvise. Okay? May be this is what @rgommers suggested. Here is a first shot that might be of help to you.
> <img alt="Screenshot 2020-01-06 at 10 46 43 AM" width="847" src="https://user-images.githubusercontent.com/5890484/71796893-fcdcfc00-3071-11ea-8b98-765678cf53b7.png">

That would be great, @shaloo !  Thank you!

**Comment by InessaPawson** [comment]
> I've only focussed on content - I'll leave it to you to wave your layout magic wand :-)

Actually, it is @joelachance who is a chief magician in that department.:)

**Comment by shaloo** [comment]
@rgommers, @joelachance, @InessaPawson  - I don't see any case studies in master (localhost:1313, using last commit 8a13aad Update crowdin.yml) or any pending updates to be merged in open PR list. 

 Is someone working on adding basic tiles with default content shown above?  Or is it part of some other issue/PR that is not yet merged? Just wanted to figure out if there is anything I can do to help adding / updating case studies related content on the landing page.

**Comment by rgommers** [comment]
@shaloo no there are no case studies yet, we want to add some. please note that the tile widgets for the front page are an independent task from pages with the actual case studies. The former is gh-129, the latter is this issue.

Given that a nice case study is quite a bit of work, I suggest to start with a single one (the black hole one, since you already have a part of the content for it). The way to do it is:
- Create a new file `content/en/case-studies/blackhole-image.md`
- Start it off with the standard metadata (see below)
- Then create the content as a self-contained story (text + images)
- This will render just fine without doing anything to the homepage. Just do the normal `hugo` then `hugo server`, the page will show up at `localhost:1313/blackhole-image`

Metadata:
```
---
title: Case Study: the first black hole image eve rmade
sidebar: false
---
```

**Comment by rgommers** [comment]
Regarding the other NumFOCUS case studies: I would not just copy those, and certainly not without asking. The CellProfiler one is nice, the other one I'm less sure about. Either way, I'd prefer to come up with a single new one. LIGO would make an obvious choice, the one downside it's physics just like the EHT black hole story. There's other options, see e.g. the "Current usage and impact" section of https://figshare.com/articles/Mid-Scale_Research_Infrastructure_-_The_Scientific_Python_Ecosystem/8009441. Let me know what you think!

**Comment by shaloo** [comment]
> @shaloo no there are no case studies yet, we want to add some. please note that the tile widgets for the front page are an independent task from pages with the actual case studies. The former is [gh-129](https://github.com/numpy/numpy.org/issues/129), the latter is this issue.
> 
> Given that a nice case study is quite a bit of work, I suggest to start with a single one (the black hole one, since you already have a part of the content for it). The way to do it is:
> 
> * Create a new file `content/en/case-studies/blackhole-image.md`
> * Start it off with the standard metadata (see below)
> * Then create the content as a self-contained story (text + images)
> * This will render just fine without doing anything to the homepage. Just do the normal `hugo` then `hugo server`, the page will show up at `localhost:1313/blackhole-image`
> 
> Metadata:
> 
> ```
> ---
> title: Case Study: the first black hole image eve rmade
> sidebar: false
> ---
> ```

Alright, makes sense.

**Comment by shaloo** [comment]
> Regarding the other NumFOCUS case studies: I would not just copy those, and certainly not without asking. The CellProfiler one is nice, the other one I'm less sure about. Either way, I'd prefer to come up with a single new one. LIGO would make an obvious choice, the one downside it's physics just like the EHT black hole story. There's other options, see e.g. the "Current usage and impact" section of https://figshare.com/articles/Mid-Scale_Research_Infrastructure_-_The_Scientific_Python_Ecosystem/8009441. Let me know what you think!

This is pretty cool.  Here is how we could choose to add info about SPE and gravitational waves related scientific discovery in 2016 besides the black hole high impact case study:

Proposed outline of the showcase md (case-studies) page: 

* NumPy's versatility - application across industries and domains - short para
* Challenges in measuring NumPy impact - 3200 citations, use model by upstream consumers often not metered, downloads number inconclusive and not sufficient to capture its wide impact
* Cherry picked show case:
   - Black Hole ( gets a page on its own under content/en/case-studies/blackhole-image.md)

   - Gravitaional Waves ( There is some really cool stuff here and I plan to reach out to this Physicist and seek some NumPy quotes from her or her team if possible see https://ep2016.europython.eu/media/conference/slides/pyhton-in-gravitational-waves-research-communities.pdf)
  -  Sports analytics ( I noticed that NumPy was used in data analytics in IPL - a big time cricket thingy in India and SE Asia.  See https://gigadom.in/2018/10/28/introducing-cricpya-python-package-to-analyze-performances-of-cricketrs/ May be similar data can be obtained from other sports that use NumPy for athlete performance analysis or play/game analysis and some quotes from say ESPN(!!!?) on NumPy usage)

I'll get started on this with black hole stuff and others in the pipeline with attempts to reach out to those who actually used it and get quotes on NumPy usage.

Does that look reasonable?

**Comment by rgommers** [comment]
>     1. Gravitaional Waves ( There is some really cool stuff here and I plan to reach out to this Physicist and seek some NumPy quotes from her or her team if possible see

I like that idea, she seems like a good person to reach out to.



>     1. Sports analytics ( I noticed that NumPy was used in data analytics in IPL - a big time cricket tournament($$$) in India and SE Asia.

I like the idea of sports analytics, and +1 on cricket given that it's one of the most popular sports in India and a number of other countries. I would like to see a better showcase than https://github.com/tvganesh/cricpy though, because that is a tiny and not very well written package.

**Comment by rgommers** [comment]
> - NumPy's versatility - application across industries and domains - short para
> - Challenges in measuring NumPy impact ...

I'm wondering if this makes sense. The "NumPy's versatility" paragraph sounds good, less sure about the challenges in measuring one - that feels like it belongs more in a proposal than on the website. 

More importantly, if the design is tiles on the home page that link directly to individual show cases, then this generic page cannot easily be navigated to. So I suspect we'd be better off with just the individual pages for show cases.

**Comment by InessaPawson** [comment]
Having a case study on the application of NumPy in sports analytics is an excellent idea, @shaloo ! 
I’ve been thinking along the same lines. Showcasing the application of NumPy across various industries would engage a broader audience (hopefully some would become contributors), as well as allow to explore opportunities for commercial partnerships with a wider range of businesses.

Another idea for a case study is the application of NumPy in the automotive industry. I know Tesla AI Department relies on NumPy. Perhaps, we could reach out to them for a testimonial and materials for a case study.

**Comment by shaloo** [comment]
@InessaPawson Tesla sounds cool, can you put me in touch (via email cc) with someone who can help me get more insights on Tesla's use of NumPy?  I can use some help to build a nice case study there.

**Comment by shaloo** [comment]
> > * NumPy's versatility - application across industries and domains - short para
> > * Challenges in measuring NumPy impact ...
> 
> I'm wondering if this makes sense. The "NumPy's versatility" paragraph sounds good, less sure about the challenges in measuring one - that feels like it belongs more in a proposal than on the website.
> 
> More importantly, if the design is tiles on the home page that link directly to individual show cases, then this generic page cannot easily be navigated to. So I suspect we'd be better off with just the individual pages for show cases.

Alright, what we could do is just have a para on NumPy versatility on the TILE page itself just before the tiles and do away with the Challenges section.

**Comment by shaloo** [comment]
Here is the [raw content for Tile Page](https://docs.google.com/document/d/1DaVTwmtdj37_8QeyBsgq90yrfq4RvHu6BNIfJQ9TJzM/edit?usp=sharing)  
and here is the draft [content outline for Black hole study](https://docs.google.com/document/d/1sin8muaYCRZF9APVrJaFizq16UoQjvXrH3Vz23xgbi4/edit?usp=sharing) that will be added in numpy.org as a first draft shortly.  Once outline is finalised, I can populate it with requisite information/content available from public sourced / vetted contacts who can provide NumPy usage inputs / quotes etc. in subsequent revisions.

**Comment by shaloo** [comment]
Adding Gravitational Waves Case Study content via this issue ticket.

**Comment by rgommers** [comment]
We've got two case studies now, the EHT black hole imaging, and LIGO gravitational waves observation (gh-160).

For the third one (sports analytics) I'll open a new issue, to not keep this one growing.

**Comment by rgommers** [comment]
There's also the Tesla idea here, but not sure that we're planning on doing that any time soon?

I think we can go up to 6 case studies on the front page at least, maybe more.
