### ISSUE TITLE
NumPy shell performance

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#83]
- [x] Keep binder from loading on every page (only homepage)
- [x] Convert the current 'Run' button to an 'Enable' button so a binder instance loads only when it's wanted.
- [x] Once 'Enable' is selected, render a spinner or loading image until the kernel is loaded.

UX: 
- [ ] Have our numpy import at the top of the terminal window, but reposition the prompt below it to indicate to the user the need to import numpy.

**Comment by shaloo** [comment]
Here are some more ideas for copy / layout and example code in terminal on the landing page - refer to attached image, blue text.

<img width="1247" alt="numpy-issue83-inputs" src="https://user-images.githubusercontent.com/5890484/69939774-a9254300-1506-11ea-9fb9-4a017f788d24.png">
