### ISSUE TITLE
#Content-Review: All typos will be fixed against this ticket-issue number.

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#94]
1. Fix the spelling of 'capabilities' in Array computing page content.
2. Change "Array computing is based on arrays data structures...." to "Array computing is based on array data structures."

**Comment by rgommers** [comment]
I'll close this, main typo was fixed. @shaloo let's do any future typo fixes without an issue, just opening a PR is less overhead and they'll be merged quickly.
